HabitPay/backend

build.gradle
src/main/java/com/habitpay/habitpay/domain/member/api/MemberApi.java
src/main/java/com/habitpay/habitpay/domain/member/api/MemberProfileService.java
src/main/java/com/habitpay/habitpay/domain/member/application/MemberService.java
src/main/java/com/habitpay/habitpay/domain/member/domain/Member.java
src/main/java/com/habitpay/habitpay/domain/member/dto/MemberRequest.java
src/main/java/com/habitpay/habitpay/domain/member/dto/MemberResponse.java
src/main/java/com/habitpay/habitpay/domain/model/Image.java
src/main/java/com/habitpay/habitpay/domain/model/Response.java
src/main/java/com/habitpay/habitpay/global/config/aws/S3FileService.java
src/main/java/com/habitpay/habitpay/global/config/jwt/TokenProvider.java
src/main/java/com/habitpay/habitpay/global/config/jwt/TokenService.java
src/main/java/com/habitpay/habitpay/global/error/ErrorResponse.java
src/main/java/com/habitpay/habitpay/global/util/ImageUtil.java
src/main/resources/application-local.yaml
src/main/resources/application.yaml

- 프론트에서 프로필 이미지 업로드 시 AWS S3 에 업로드 할 수 있는 presigned url 을 발급 받아서 프론트에 응답합니다.
1. 프론트에서 이미지에 대한 정보인 용량과 파일 확장자를 받아서 S3 presigned url 을 발급 받습니다. 
- 프론트에서 올리려고 했던 이미지가 아닌 다른 파일을 올리는 것을 방지하기 위한 처리입니다.
2. 프로필 이미지 이름은 UUID v4 로 랜덤으로 생성해서 Member 테이블의 `imageFileName` 컬럼에 저장합니다.
3. 사용자가 프로필 이미지를 이미 업로드 했었다면 기존에 업로드한 파일을 S3 에서 삭제합니다.

Feat/마이페이지 이미지 저장 컨트롤러 구현#17

---

src/main/java/com/habitpay/habitpay/domain/member/api/MemberApi.java
src/main/java/com/habitpay/habitpay/domain/member/application/MemberService.java

- DELETE /member 컨트롤러 생성
- 탈퇴하려는 유저가 이미 프로필 이미지를 S3 에 업로드 했다면 삭제하도록 처리

:sparkles: feat: Implement DELETE /member controller #22

---

src/main/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApi.java
src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeCreateService.java
src/main/java/com/habitpay/habitpay/domain/challenge/dao/ChallengeRepository.java
src/main/java/com/habitpay/habitpay/domain/challenge/domain/Challenge.java
src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengeRequest.java

- 챌린지 생성 컨트롤러를 만들었습니다. (POST /challenge)
- 챌린지 생성 후 프론트에 챌린지의 ID 를 보냅니다. ID 를 이용해서 챌린지 화면으로 이동할 수 있도록 할 예정입니다.

feat: 챌린지 생성 컨트롤러 생성 #26

---

src/main/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApi.java
src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeCreationService.java
src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeSearchService.java
src/main/java/com/habitpay/habitpay/domain/challenge/domain/Challenge.java
src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengeCreationRequest.java
src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengeResponse.java

- GET /challenge/{id} 요청을 보내면 챌린지 정보를 응답하는 컨트롤러를 생성했습니다.
- 응답에 담는 데이터를`ChallengeResponse` 클래스로 생성했습니다.
- 챌린지에 참여한 사람만 챌린지에 대한 정보를 확인할 수 있도록 challenge_enrollment 테이블을 확인 후 응답을 보냅니다.
- 챌린지에 참여하는 인원, 챌린지에 참여하는 사용자의 이미지 파일 3개를 추가로 보낼 예정입니다.
- 위의 작업 모두 challenge_enrollment 도메인 생성 후 진행 예정입니다.

Feat/챌린지 조회 컨트롤러 구현#35

---

src/main/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApi.java
src/main/java/com/habitpay/habitpay/domain/challenge/domain/Challenge.java
src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengePatchRequest.java
src/main/java/com/habitpay/habitpay/global/config/auth/SecurityConfig.java

- PATCH /challenge/{id} 컨트롤러를 구현했습니다.
- 챌린지 정보를 수정하기 위한 데이터를 담는 `ChallengePatchRequest` 클래스를 생성했습니다.
- 현재는 챌린지 설명(description)만 수정 가능하도록 했습니다. 
- `SecurityConfig` 파일에서 Request 의 모든 하위 경로를 받을 수 있도록 * 에서 ** 로 수정했습니다.

Feat/챌린지 정보 수정 기능 구현#40

---

src/main/java/com/habitpay/habitpay/domain/challengePost/api/ChallengePostApi.java
src/main/java/com/habitpay/habitpay/domain/challengePost/application/ChallengePostService.java
src/main/java/com/habitpay/habitpay/domain/challengePost/dao/ChallengePostRepository.java
src/main/java/com/habitpay/habitpay/domain/challengePost/dto/PostViewResponse.java
src/main/java/com/habitpay/habitpay/domain/postPhoto/application/PostPhotoService.java

* `ChallengePost` 컨트롤러 및 서비스 로직 리팩토링
-----
* `GET /challenge_enrollment/{id}/posts` 메서드 생성
```java
@GetMapping("/challenge_enrollment/{id}/posts")
public ResponseEntity<List<PostViewResponse>> findChallengeEnrollmentPosts(@PathVariable Long id) {
List<PostViewResponse> posts = challengePostService.findAllByChallengeEnrollment(id)
.stream()
.map(post -> new PostViewResponse(post, postPhotoService.makePhotoViewList(postPhotoService.findAllByPost(post.getId()))))
.toList();
return ResponseEntity.ok()
.body(posts);
}
```
* `challenge_enrollment`는, 특정 챌린지에 등록했을 때 생성되는 entity
-> `challengeEnrollmentId`를 통해, 한 챌린지 내의 나의 행적을 파악할 수 있음
-> 한 챌린지 내에서 내가 쓴 포스트만 모아서 추적 가능
* 위의 메서드는 한 챌린지 내에서 '내 글 모아보기' 기능을 지원
* `challengeEnrollmentId`를 통해 내가 쓴 `포스트 list`를 얻음
-> 각 `포스트` 별로 해당 포스트에 포함된 `photo list`를 얻음 …

[feat] ChallengePost : 특정 챌린지 내에서 내가 쓴 포스트만 모아보기 기능 #46

---

src/main/java/com/habitpay/habitpay/domain/challengePost/api/ChallengePostApi.java
src/main/java/com/habitpay/habitpay/domain/postPhoto/application/PostPhotoService.java
src/main/java/com/habitpay/habitpay/domain/postPhoto/domain/PostPhoto.java
src/main/java/com/habitpay/habitpay/domain/postPhoto/dto/PostPhotoData.java

* 해당 이슈 및 브랜치 내용은, 금일 스크럼 때 준한님이 (aws 환경 설정을 도와주시면서 겸사) 알려주신 외래키 연결법 및 같이 진행한 코드 수정을 반영한 것입니다.
`PostPhoto` 엔티티에 챌린지 포스트가 외래키로 연결된 모습
```java
@ManyToOne
@JoinColumn
private ChallengePost post;
```
관련되어있는 DTO 및 메서드를 맞게 수정함
-----
* 별개로, `findById 시리즈 메서드`에서 인자로 받은 id에 해당하는 데이터가 없을 시,
`IllegalArgumentException`가 아닌 `NoSuchElementException`를 던지도록 수정

[feat] PostPhoto에 ChallengePost를 외래키로 연결 #48

---

src/main/java/com/habitpay/habitpay/domain/challengePost/api/ChallengePostApi.java
src/main/java/com/habitpay/habitpay/domain/challengePost/application/ChallengePostService.java
src/main/java/com/habitpay/habitpay/domain/challengePost/domain/ChallengePost.java
src/main/java/com/habitpay/habitpay/domain/challengePost/dto/AddPostRequest.java
src/main/java/com/habitpay/habitpay/domain/challengePost/dto/ModifyPostRequest.java
src/main/java/com/habitpay/habitpay/domain/challengePost/dto/PostViewResponse.java
src/main/java/com/habitpay/habitpay/domain/postPhoto/application/PostPhotoService.java
src/main/java/com/habitpay/habitpay/domain/postPhoto/dao/PostPhotoRepository.java
src/main/java/com/habitpay/habitpay/domain/postPhoto/domain/PostPhoto.java
src/main/java/com/habitpay/habitpay/domain/postPhoto/dto/AddPostPhotoData.java
src/main/java/com/habitpay/habitpay/domain/postPhoto/dto/ModifyPostPhotoData.java
src/main/java/com/habitpay/habitpay/domain/postPhoto/dto/PostPhotoView.java
src/main/java/com/habitpay/habitpay/global/error/CustomJwtErrorInfo.java
src/main/java/com/habitpay/habitpay/global/exception/JWT/CustomJwtException.java

* 소소한 리팩토링
-----
* 클래스 내 변수명을 코드 커스텀에 맞게 카멜 케이싱으로 변경
```java
Message -> message
```
-----
```java
@PutMapping("/api/posts/{id}")
public ResponseEntity<List<String>> modifyPost(@PathVariable Long id,
@RequestBody ModifyPostRequest request) {
ChallengePost modifiedPost = challengePostService.update(id, request);
request.getDeletedPhotoIds().forEach(postPhotoService::delete);
request.getModifiedPhotos().forEach(photo -> postPhotoService.changeViewOrder(photo.getPhotoId(), photo.getViewOrder()));
List<String> presignedUrlList =  postPhotoService.save(challengePostService.findById(id), request.getNewPhotos());
return ResponseEntity.ok()
.body(presignedUrlList);
}
```
* 챌린지 포스트 수정에는 크게 4가지 변경이 있다고 상정
: 1. 내용(`content`) 변경
2. 이미지 파일 삭제
3. 이미지 파일 순서 변경
4. 새 이미지 파일 추가
* 리턴 타입은 `presignedUrl`(S3에 …

[feat] 챌린지 포스트 내용을 수정하는 PUT 메서드 제작 #45

---

src/main/java/com/habitpay/habitpay/domain/challengePost/api/ChallengePostApi.java
src/main/java/com/habitpay/habitpay/domain/challengePost/domain/ChallengePost.java
src/main/java/com/habitpay/habitpay/domain/challengePost/dto/PostViewResponse.java
src/main/resources/application-local.yaml

* 컨벤션 정해지기 전에 작업한 도메인 : `ChallengePost`, `PostPhoto`, `RefreshToken`
* 그 중 API가 있는 도메인 : `ChallengePost`, `RefreshToken`
* `RefreshToken`의 컨트롤러
```java
@PostMapping("/token")
```
뿐이어서 다행히 수정할 게 없었음
-> 결론 : `ChallengePost`만 수정하면 됨
-----
* 주석처리했던 `/api`를 다시 살림
-> 이제 요청 시 `JWT`를 `Bearer Token`으로 추가해서 보내야 처리됨
```java
//  특정 id의 포스트 불러오기
@GetMapping("/api/posts/{id}")
public ResponseEntity<PostViewResponse> findPost(@PathVariable Long id)
// 특정 챌린지 내 모든 포스트 불러오기
// `?challengeEnrollmentId=` 쿼리 스트링이 있다면, 해당 등록 멤버의 포스트만 불러오기
@GetMapping("/api/challenges/{id}/posts")
public ResponseEntity<List<PostViewResponse>> findChallengePosts(
@PathVariable Long id,
@RequestParam(required = false) Optional<Long> challengeEnrollmentId)
// 특정 id의 포스트 수정하기
@PutMapping("/api/posts/{id}")
// 특정 id의 포스트 삭제하기 …
```

[refact] REST API 네이밍 컨벤션에 맞추어 ChallengePost 컨트롤러 수정하기 #53

---

src/main/java/com/habitpay/habitpay/domain/challengePost/api/ChallengePostApi.java
src/main/java/com/habitpay/habitpay/domain/challengePost/application/ChallengePostService.java
src/main/java/com/habitpay/habitpay/domain/challengePost/domain/ChallengePost.java

* 챌린지 포스트 모아보는 GET 컨트롤러 메서드 수정
```java
// 이전 코드
@GetMapping("/api/challenges/{id}/posts")
public ResponseEntity<List<PostViewResponse>> findChallengePosts(
@PathVariable Long id, @RequestParam(required = false) Optional<Long> challengeEnrollmentId) {
// "/api/challenges/{id}/posts"로 들어오면 챌린지 내 모든 포스트 모아보기
// "/api/challenges/{id}/posts?challengeEnrollmentId="로 들어오면, 챌린지 내 해당 멤버의 모든 포스트 모아보기
//                                                  -> enrollment id 통해 '내 글 보기', '특정 멤버 글 보기' 모두 처리
}
```
```java
// 바뀐 코드
@GetMapping("/api/challenges/{id}/posts")
public ResponseEntity<List<PostViewResponse>> findChallengePosts(@PathVariable Long id) {
// 챌린지 내 모든 글 모아보기
}
...
@GetMapping("/api/challenges/{id}/posts/me")
public ResponseEntity<List<PostViewResponse>> findChallengePostsByMe( …
```

[feat] 챌린지 포스트 컨트롤러 수정 and 포스트 수정 요청 시 필요한 null 예외 처리 추가 #60

---

src/main/java/com/habitpay/habitpay/domain/challengepost/api/ChallengePostApi.java
src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostService.java
src/main/java/com/habitpay/habitpay/domain/challengepost/dao/ChallengePostRepository.java
src/main/java/com/habitpay/habitpay/domain/challengepost/domain/ChallengePost.java
src/main/java/com/habitpay/habitpay/domain/challengepost/dto/AddPostRequest.java
src/main/java/com/habitpay/habitpay/domain/challengepost/dto/ModifyPostRequest.java
src/main/java/com/habitpay/habitpay/domain/challengepost/dto/PostViewResponse.java
src/main/java/com/habitpay/habitpay/domain/postphoto/application/PostPhotoService.java
src/main/java/com/habitpay/habitpay/domain/postphoto/dao/PostPhotoRepository.java
src/main/java/com/habitpay/habitpay/domain/postphoto/domain/PostPhoto.java
src/main/java/com/habitpay/habitpay/domain/postphoto/dto/AddPostPhotoData.java
src/main/java/com/habitpay/habitpay/domain/postphoto/dto/ModifyPostPhotoData.java
src/main/java/com/habitpay/habitpay/domain/postphoto/dto/PostPhotoView.java
src/main/java/com/habitpay/habitpay/domain/postphoto/exception/CustomPhotoException.java
src/main/java/com/habitpay/habitpay/domain/proof/dao/ProofRepository.java
src/main/java/com/habitpay/habitpay/domain/proof/domain/Proof.java
src/main/java/com/habitpay/habitpay/domain/refreshtoken/api/TokenApiController.java
src/main/java/com/habitpay/habitpay/domain/refreshtoken/application/NewTokenService.java
src/main/java/com/habitpay/habitpay/domain/refreshtoken/application/RefreshTokenService.java
src/main/java/com/habitpay/habitpay/domain/refreshtoken/dao/RefreshTokenRepository.java
src/main/java/com/habitpay/habitpay/domain/refreshtoken/domain/RefreshToken.java
src/main/java/com/habitpay/habitpay/domain/refreshtoken/dto/CreateAccessTokenRequest.java
src/main/java/com/habitpay/habitpay/domain/refreshtoken/dto/CreateAccessTokenResponse.java
src/main/java/com/habitpay/habitpay/domain/refreshtoken/exception/CustomJwtException.java

* #63 이슈에서 패키지 이름을 모두 소문자로 변경했으나, 각 파일 상단의 `package 경로`와 `import 경로`는 수정되지 않은 것을 발견해 고침
* 패키지 이름 변경 : intelliJ의 `refactor -> rename` 기능 사용
* `rename` 시 설정 : [`comments`와 `strings`에서도 찾아 바꾸겠다]는 옵션을 선택하지 않았음 (일반 변수명도 바뀌면 안 되니까,,)
* import 등의 경로도 알아서 바꿔주는 줄 알았으나 아니었음
* Proof 도메인 만들며 클래스 참조가 제대로 안 되는 현상을 뒤늦게 발견하고 고침,,
-----
* `Proof` 도메인을 위한 패키지를 만들고, `entity` 및 `repository` 기본 틀로만 파일 만듦
* 일단 도메인 이름을 `Proof`로 한 이유
: 원안인 `Participation`은 챌린지 자체에 참여한다는 의미로도 읽힐 수 있음
-> 그 경우 `Enrollment`와 겹쳐 혼동될 수 있음
-> 챌린지 내 과제에 참여했고 미션 성공으로 인정 받았다는 '증거'의 의미로 `proof` 채택
* 그러나 언제나 더 적절하고 좋은 이름이 있다면 바꿀 의향이 있습니다,,!

[Feat] 패키지 이름 변경 오류 수정 & proof 도메인 패키지 만들기 #64

---

src/main/java/com/habitpay/habitpay/domain/challengeenrollment/api/ChallengeEnrollmentApi.java
src/main/java/com/habitpay/habitpay/domain/challengeenrollment/application/ChallengeEnrollmentService.java
src/main/java/com/habitpay/habitpay/domain/challengeenrollment/dao/ChallengeEnrollmentRepository.java
src/main/java/com/habitpay/habitpay/domain/challengeenrollment/domain/ChallengeEnrollment.java

- 사용자의 챌린지 참여를 위한 `challengeEnrollment` 도메인을 생성했습니다.
- POST `/challenges/{id}/enroll` 컨트롤러에서 사용자의 챌린지 참여를 받을 수 있도록 구현했습니다.
현재는 컨트롤러에서 `@RequestHeader` 어노테이션을 통해 authorization header 에 포함된 jwt 토큰에서 사용자의 이메일을 획득합니다.
하지만 모든 컨트롤러에서 동일한 코드를 반복하는 것은 비효율적인 것 같아서 filter 나 interceptor 에서 사용자 정보를 먼저 등록하고, 컨트롤러나 서비스에서는 등록한 정보를 가져오는 방식으로 구현하는 것이 가능할 지 찾아보고 있습니다.
컨트롤러의 반환 값을 무엇이든 돌려줄 수 있도록 `<?>` 을 이용했습니다.
하지만 명확한 반환 값을 정의하는 것이 코드를 한 번에 이해하기 좋고, 유지보수 측면에서도 좋을 것 같다는 생각이 들었습니다.
그래서 `ApiResponse` 와 같은 클래스를 이용해서 공통된 response 규격을 정의하고, 각 도메인에서 필요한 응답은 `ApiResponse` 클래스를 상속 받아서 새롭게 생성하는 것은 어떨지 생각하고 있습니다.

:sparkles: feat: 챌린지 참여 도메인 생성 및 챌린지 참여 컨트롤러 구현  #58

---

src/main/java/com/habitpay/habitpay/domain/challengeparticipationrecord/dao/ChallengeParticipationRecordRepository.java
src/main/java/com/habitpay/habitpay/domain/challengeparticipationrecord/domain/ChallengeParticipationRecord.java
src/main/java/com/habitpay/habitpay/domain/proof/dao/ProofRepository.java

* 도메인 이름 변경
: 의미가 더 명확한 이름으로 변경되었습니다.
```java
Proof -> ChallengeParticipationRecord
```
* `ChallengeParticipationRecord`가 자체 지역 변수 `createdAt`을 사용하는 대신, `BaseTime`을 상속 받아 `createdAt` 요소를 사용합니다.
```java
public class ChallengeParticipationRecord extends BaseTime { }
```
-----
* 이야기해보고 싶은 것
* `ChallengeParticipationRecord`은 도메인 특성 상, 생성만 가능하고 변경이나 삭제는 불가능하다는 원칙을 세웠습니다.
그래서 `createdAt` 요소만 필요하다고 판단, 처음에는 생성 일시만 도메인 내 지역 변수로 설정했습니다.
그러나 코멘트 해주신 것에 따라 이미 만든 걸 재사용하는 게 일리가 있다고 판단해 이번 풀리퀘에서 `BaseTime`을 상속받는 방식으로 수정했는데요,
막상 고치고 보니, 사용하지 않을 `BaseTime`의 `modifiedAt`, `deletedAt`이 마음에 걸립니다ㅠㅠ.
상속 받은 부모 클래스의 특정 요소를 사용하지 못하도록 막는 기능이 있나 검색해봤으나 짧은 시간 내에 찾지는 못했고,,
이게 상속을 제대로 사용하고 있는 것인지 확신이 안 들고,, (이건 제가 정말 잘 모르기 때문에)
그럼에도 `BaseTime`을 상속 받아서 사용하는 게 더 유용할 것인지 한 번 더 고견을 여쭙고 싶습니다.
(이번에도 동일한 코멘트 받으면 바로 머지하려고 …

[feat] 도메인 수정 : Proof -> ChallengeParticipationRecord #73

---

src/main/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApi.java
src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengeResponse.java
src/main/java/com/habitpay/habitpay/domain/challengeenrollment/application/ChallengeEnrollmentSearchService.java

프론트에서 사용자가 챌린지 참여했는지 판단하기 위해 `isEnrolledMember` 멤버변수를 `ChallengeResponse` DTO 에 추가했습니다.
```diff
@Getter
public class ChallengeResponse {
private String title;
private String description;
private ZonedDateTime startDate;
private ZonedDateTime endDate;
private byte participatingDays;
private int feePerAbsence;
private String hostNickname;
private String hostProfileImage;
private Boolean isHost;
+   private Boolean isEnrolledMember;
}
```
해당 변수는 Challenge 에 참여한 여부인 ChallengeEnrollment 가 존재하는지 확인한 후 값을 결정합니다.
```java
if (optionalChallengeEnrollment.isEmpty()) {
this.isEnrolledMember = false;
} else {
ChallengeEnrollment challengeEnrollment = optionalChallengeEnrollment.get();
this.isEnrolledMember = challengeEnrollment.getChallenge().getId().equals(challenge.getId());
}
``` …

Feat/챌린지 정보 조회 컨트롤러 수정#75

---

src/main/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApi.java
src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeCreationService.java
src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeDetailService.java
src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeUpdateService.java
src/main/java/com/habitpay/habitpay/domain/challenge/domain/Challenge.java

대상 컨트롤러는 아래와 같이 3가지입니다.
GET /challenges/{id}
POST /challenge
PATCH /challenge/{id}
POST /challenge -> /challenges
PATCH /challenge/{id} -> /challenges/{id}
도메인 객체(Challenge)의 일부 정보만 변경하고 싶을 때 `repository.save()` 를 실행해도 update 가 이루어진다고 합니다.
JPA 에는 update 메서드가 존재하지 않는데, save 메서드가 DB 의 primary key 를 참고해서 새롭게 생성하는 객체인지, 업데이트하는 객체인지 추적한다고 합니다. (자세한 원리는 아직 이해하지 못함)
- 참고자료: [Save는 Insert와 Update를 어떻게 구분할까](https://brunch.co.kr/@anonymdevoo/37) [브런치]

Refactor/챌린지 컨트롤러 서비스 로직 분리#77

---

src/main/java/com/habitpay/habitpay/domain/challengepost/api/ChallengePostApi.java
src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostService.java
src/main/java/com/habitpay/habitpay/domain/challengepost/dao/ChallengePostRepository.java
src/main/java/com/habitpay/habitpay/domain/challengepost/domain/ChallengePost.java
src/main/java/com/habitpay/habitpay/domain/challengepost/dto/AddPostRequest.java

* 포스트 등록 시 `isAnnouncement`가 `true`라면, `요청 토큰의 주인`이 `해당 챌린지의 호스트`인 경우에만 등록 가능하도록 수정
```java
@PostMapping("/api/challenges/{id}/post")
public ResponseEntity<List<String>> addPost(@RequestBody AddPostRequest request, @PathVariable Long id, @AuthenticationPrincipal String email) {
// 디버깅 용도
log.info("Authentication Principal Email: {}", email);
// @AuthenticationPrincipal email 데이터와 챌린지 id를 이용해, enrollment 파악
// (현재는 findByMember()가 List<>가 아닌 enrollment 단일 객체만 반환하므로, 아직 챌린지 id는 안 쓰였음)
// (멤버가 여러 챌린지에 등록하면, 멤버 한 명에 연결된 enrollment도 n개가 됨 -> List<>로 받아야 될 상황 생김)
// (나중에 List<ChallengeEnrollment>가 반환되면, 그 중에 챌린지 id 동일한 것을 골라 쓰면 됨)
Member member = memberService.findByEmail(email);
ChallengeEnrollment enrollment = challengeEnrollmentSearchService.findByMember(member)
.orElseThrow(() -> new …
```

[Feat] host만이 공지 포스트를 등록하고 삭제할 수 있게 함 #79

---

src/main/java/com/habitpay/habitpay/domain/challengepost/api/ChallengePostApi.java
src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostService.java

* `getWriter()`는 포스트의 작성자를 찾기 위한 메서드
```java
public Member getWriter(ChallengePost post) { }
```
---
* `authorizePostWriter()`는 포스트의 작성자가 맞는지 검증하는 메서드
```java
public void authorizePostWriter(ChallengePost challengePost) {
String email = SecurityContextHolder.getContext().getAuthentication().getName();
if (!getWriter(challengePost).getEmail().equals(email)) {
throw new CustomJwtException(HttpStatus.UNAUTHORIZED, CustomJwtErrorInfo.UNAUTHORIZED, "Not a Member who posted.");
}
}
```
포스트 수정 및 삭제 시, 작성자 본인이 맞는지 검증이 필요하기 때문에 제작.
컨트롤러를 통해 얻은 `포스트 id`를 `SecurityContextHolder`의 `토큰 email` 정보와 결합해서 확인함.
-> 이때 `getWriter()` 이용
---
* 포스트 수정 및 삭제 메서드 리팩토링 중, 작성자 인증 뿐만 아니라 챌린지의 호스트인지 판단도 필요하다는 걸 알게 됨.
* `isHost()` 메서드 오버로딩 시리즈를 만들게 됨.
```java
public boolean isHost(Challenge challenge, Member member) { …
```

[feat] getWriter() 메서드를 사용하는 로직들 수정 및 리팩토링 #81

---

src/main/java/com/habitpay/habitpay/domain/challengeparticipationrecord/application/ChallengeParticipationRecordSearchService.java
src/main/java/com/habitpay/habitpay/domain/challengeparticipationrecord/application/ChallengeParticipationRecordService.java
src/main/java/com/habitpay/habitpay/domain/challengeparticipationrecord/domain/ChallengeParticipationRecord.java
src/main/java/com/habitpay/habitpay/domain/challengepost/api/ChallengePostApi.java
src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostService.java

* `ChallengeParticipationRecord` 도메인의 `enrollment` 요소를 외래키로 연결함
```java
public class ChallengeParticipationRecord extends BaseTime {
...
@ManyToOne
@JoinColumn
private ChallengeEnrollment enrollment;
...
}
```
---
* addPost 메서드에 트랜잭션 어노테이션 추가
```java
@Transactional
@PostMapping("/api/challenges/{id}/post")
public ResponseEntity<List<String>> addPost(@RequestBody AddPostRequest request, @PathVariable Long id, @AuthenticationPrincipal String email) { }
```
포스트와 사진 저장, 레코드 생성까지 여러 단계가 얽혀있고 한 세트로 진행되어야 해서 추가함
(트랜잭션의 쓰임새를 다 알지 못해서, 추후 수정할지도.)
---
* `application/ChallengeParticipationRecordService.java` 추가
```java
public ChallengeParticipationRecord save(ChallengeEnrollment enrollment, ChallengePost post) {
return challengeParticipationRecordRepository.save( …
```

[feat] 포스트가 저장될 때 챌린지 참여 기록 객체도 생성 및 저장하기 #83

---

src/main/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApi.java
src/main/java/com/habitpay/habitpay/domain/challengeenrollment/api/ChallengeEnrollmentApi.java
src/main/java/com/habitpay/habitpay/global/config/auth/interceptor/AuthorizationInterceptor.java

기존에는 컨트롤러에서 request method, uri 를 출력하던 로그를 `AuthorizationInterceptor` 에서 출력하도록 했습니다. 
```diff
@RestController
+ @RequestMapping("/api")
@RequiredArgsConstructor
@Slf4j
public class ChallengeApi {
@ResponseStatus(HttpStatus.OK)
public ResponseEntity<ChallengeResponse> getChallengeDetail(@PathVariable("id") Long id,
@AuthenticationPrincipal String email) {
-         log.info("[GET /challenges/{}]", id);
return challengeDetailService.findById(id, email);
}
```
```java
// AuthorizationInterceptor.java`
@Override
public boolean preHandle(
HttpServletRequest request,
HttpServletResponse response,
Object handler) throws Exception {
...
log.info("[{} {}] email: {}", request.getMethod(), request.getRequestURI(), authentication.getPrincipal());
}
```
출력 예시는 아래와 같습니다.
```
[POST …
```

:recycle: refactor: request method, uri 로그 출력 

---

src/main/java/com/habitpay/habitpay/domain/challengepost/api/ChallengePostApi.java
src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostService.java

* `특정 멤버`가 `특정 챌린지`의 `Host`인지 아닌지 판별하는 메서드의 이름을 변경했습니다.
```java
isHost() => isChallengeHost()
```
* 기존에 있던 메서드를 활용해 `isChallengeHost()`의 오버로딩 개수를 줄일 수 있어 그렇게 했습니다.
```java
public boolean isChallengeHost(Challenge challenge, Member member) { }
public boolean isChallengeHost(Challenge challenge, String email) { }
```
* 줄이고 나니, `Member`의 `getEmail() 메서드`를 이용하거나 email을 이용해 Member 객체를 얻는 방식을 사용하면,
하나의 `isChallengeHost()`만으로 충분하다는 생각도 드네요,,!
의미상 `Member` 객체가 들어가는 게 정확해보이긴 하는데, 함수 하나라도 덜 쓸 수 있을까 싶어서 오버로딩으로 만들었던 거라 조금 고민이 됩니다.
필요하면 언제든 더 리팩토링 하겠습니다.

[refactor] isHost() 메서드의 이름을 isChallengeHost()로 변경#89

---

src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostService.java

* `챌린지 포스트`의 `content`나 `isAnnouncement` 값에 변경이 있을 시, DB에 반영하기 위한 `save` 메서드 코드를 추가했습니다.
```java
...
challengePost.modifyPostContent(request.getContent());
challengePostRepository.save(challengePost);
...
...
challengePost.modifyPostIsAnnouncement(request.getIsAnnouncement());
challengePostRepository.save(challengePost);
...
```
---
* `isChallengeHost()` 메서드 중 하나의 가독성을 높이기 위해 return문에 모든 코드를 우겨넣는 대신,
`hostEmail` 변수에 한 번 값을 받은 후에 처리하는 것으로 리팩토링 했습니다.
```java
public boolean isChallengeHost(Challenge challenge, String email) {
String hostEmail = challenge.getHost().getEmail();
return hostEmail.equals(email);
}
```

[feat] 챌린지 포스트 변경 시 repository에 save하는 코드 추가#91

---

src/main/java/com/habitpay/habitpay/domain/challengepost/api/ChallengePostApi.java
src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostCreationService.java
src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostDeleteService.java
src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostSearchService.java
src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostUpdateService.java
src/main/java/com/habitpay/habitpay/domain/postphoto/application/PostPhotoDeleteService.java

* 서비스 메서드의 이름을, 컨트롤러 메서드에서 바로 사용해도 의미가 명확히 전달될 수 있도록 변경했습니다.
```java
// ex)
public List<String> addPost(...) { }
=>    public List<String> save(...) { }
public void deletePost(...) { }
=>    public void delete(...) { }
public PostViewResponse findPost(...) { }
=>    public PostViewResponse findPostById(...) { }
...
```
---
* 관련하여 서비스 내의 다른 메서드와 이름이 겹칠 경우, private 메서드 `save -> savePost` 식으로 코드 내에서 작동하는 내용이 뭔지 더 드러나도록 변경했습니다.
```java
// ex
@Transactional
public List<String> save(...) {
포스트가 공지글인지 아닌지 확인,
포스트가 record로 등록되어야 하는지 아닌지 확인,
사진들도 따로 저장,
savePost() 메서드 호출 등
}
private ChallengePost savePost(AddPostRequest request, Long challengeEnrollmentId) {
...
// 포스트 저장만 하는 메서드여서 이름이 savePost
return challengePostRepository.save(request.toEntity(challengeEnrollmentId));
}
```
---
* 하나의 메서드가 너무 많은 …

[Refactor] 서비스 메서드의 이름을 더 명확하게 바꾸기 #97

---

src/main/java/com/habitpay/habitpay/domain/challengeparticipationrecord/application/ChallengeParticipationRecordSearchService.java
src/main/java/com/habitpay/habitpay/domain/challengeparticipationrecord/dao/ChallengeParticipationRecordRepository.java
src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostCreationService.java
src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostUtilService.java

* 챌린지 `포스트` 업로드 시, 특정 조건을 달성하면 `record 객체`가 새로 생성 및 저장되어야 함
* 특정 조건 :
```java
1. 포스트 업로드 된 날짜가 챌린지 진행 기간 이내면서,
2. 챌린지의 참여 요일이면서, (ex. 월요일 인증 챌린지면 업로드된 날짜의 요일이 월요일이어야 함)
3. 해당 날짜에 아직 record 객체가 없다면 (=== 아직 그날의 인증 포스트가 없다면)
=> ChallengeParticipationRecord 객체를 생성 및 저장함
(해당 Challenge 객체의 numberOfParticipants 속성도 +1 할 예정)
```
---
* 해당 로직은 `포스트 저장 메서드` 내의 `verifyChallengeParticipationRecord` 메서드를 통해 이루어짐
```java
@Transactional
public List<String> save(AddPostRequest request, Long challengeId, String email) {
...
challengePostUtilService.verifyChallengeParticipationRecord(challengePost, enrollment);
...
}
```
---
```java
// (로직 흐름이 보이게 하기 위해 코드를 거칠게 잘랐습니다.)
public void verifyChallengeParticipationRecord(...) {
// 챌린지 기간 내인지 확인
if (!now.isAfter(challenge.getStartDate()) || …
```

[feat] 포스트 업로드 시 record 객체 생성 로직 초안 #101

---

src/main/java/com/habitpay/habitpay/domain/postphoto/application/PostPhotoCreationService.java

* 이전 경로 : `challenges`
* 바꾼 경로 : `challenges/{challenge_id}/{post_id}`
* 로직 : `postPhotoUtilService`의 `makeS3TargetPath` 메서드 활용

[feat] 챌린지 포스트의 postPhoto 저장 시, S3에 업로드 되는 경로 이름 구체화하기 #104

---

src/main/java/com/habitpay/habitpay/domain/challengeparticipationrecord/application/ChallengeParticipationRecordSearchService.java
src/main/java/com/habitpay/habitpay/domain/challengeparticipationrecord/dao/ChallengeParticipationRecordRepository.java
src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostCreationService.java
src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostUtilService.java

* 업로드한 `포스트`가 `record`로 인정되는지 검증하기 위해,
해당 `업로드일에 이미 등록된 record`가 있는지 여부를 확인하는 메서드가 필요함
-> `alreadyParticipateToday`
* 이 메서드를 단순화하기 위해 쿼리 메서드 추가
```java
Optional<ChallengeParticipationRecord> findByChallengeEnrollmentAndCreatedAtBetween
(ChallengeEnrollment enrollment, LocalDateTime startOfDay, LocalDateTime endOfDay);
```
* 해당 `enrollment` 소속 중에 `포스트 CreatedAt` 날짜에 해당하는 객체가 있는지 검색하는 메서드 추가
---
* 동명의 메서드를 record search sevice에 추가
```java
public Optional<ChallengeParticipationRecord> findByChallengeEnrollmentAndCreatedAtBetween(
ChallengeEnrollment enrollment,
LocalDateTime startOfDay,
LocalDateTime endOfDay) {
return challengeParticipationRecordRepository.findByChallengeEnrollmentAndCreatedAtBetween(
enrollment,
startOfDay,
endOfDay
);
}
```
---
* 위의 메서드 사용으로 `alreadyParticipateToday`가 …

[feat] 쿼리 메서드를 이용해 alreadyParticipateToday 메서드 단순화하기 #107

---

.github/workflows/api-docs.yaml
build.gradle
src/docs/asciidoc/api/member.adoc
src/docs/asciidoc/index.adoc
src/docs/asciidoc/test.adoc
src/main/java/com/habitpay/habitpay/HabitpayApplication.java
src/main/java/com/habitpay/habitpay/domain/challenge/domain/Challenge.java
src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengeResponse.java
src/main/java/com/habitpay/habitpay/domain/member/api/MemberApi.java
src/main/java/com/habitpay/habitpay/domain/member/application/MemberSearchService.java
src/main/java/com/habitpay/habitpay/domain/member/dto/MemberResponse.java
src/main/java/com/habitpay/habitpay/domain/restdocs/RestDocsController.java
src/main/java/com/habitpay/habitpay/global/config/JpaConfiguration.java
src/test/java/com/habitpay/habitpay/HabitpayApplicationTests.java
src/test/java/com/habitpay/habitpay/RestDocsControllerTest.java
src/test/java/com/habitpay/habitpay/docs/springrestdocs/AbstractRestDocsTests.java
src/test/java/com/habitpay/habitpay/member/api/MemberApiTest.java
src/test/resources/application.yaml

- Spring Rest Docs 를 이용해서 API 명세서를 자동으로 작성하고, 이를 Github Pages ([링크](https://habitpay.github.io/backend/)) 로 배포할 수 있도록 Github Actions 설정을 추가했습니다.
- 테스트 케이스에 통과한 컨트롤러에 대해서만 API 명세서를 생성합니다.
- 현재는 테스트 목적으로 작성한 컨트롤러에 대해서만 API 명세서만 작성되어있는 상태입니다.
- 자세한 작업 내용은 아래의 링크로 대체합니다.
- 링크: [[Spring] Spring Rest Docs 적용 및 Github Pages 자동 배포](https://han-joon-hyeok.github.io/posts/java-spring-rest-docs-with-deploying-github-pages/)

Chore/spring rest docs 적용#102

---

src/main/java/com/habitpay/habitpay/global/config/auth/CorsConfig.java
src/main/java/com/habitpay/habitpay/global/config/auth/interceptor/AuthorizationInterceptor.java
src/main/java/com/habitpay/habitpay/global/config/auth/interceptor/SignUpInterceptor.java

* 이전 코드 : `POST /api/member` 경로를 처리하는 `signUp 인터셉터`와, `/api/**` 경로를 처리하는 `인증 인터셉터`가 각각 존재
-> `/api/member`가 `signUp 인터셉터`를 거치고 난 후, `인증 인터셉터` 역시 거치는 문제 발생
(사실 특별한 설정이 없으면, 메서드는 등록된 모든 인터셉터를 차례로 거치게 되어 있음)
---
* 시도 : 패턴 구체화를 통해 해결하고자 함
`excludePathPatterns()` 메서드를 이용해 `인증 인터셉터`가 `/api/member`를 처리하지 않도록 하기
```java
registry.addInterceptor(authorizationInterceptor())
.addPathPatterns("/api/**")
.excludePathPatterns("/api/member");
```
---
* 발생한 문제 : `/api/member`에는 `signUp 인터셉터`을 거치는 `POST 메서드` 뿐만 아니라, `인증 인터셉터`를 거쳐야 하는` GET, PATCH, DELETE `등 다른 메서드도 존재함.
다른 메서드들이 원래 거쳐야 할 `인증 인터셉터`를 거르고 `signUp 인터셉터`만을 거치는 문제 발생
---
* 서치해봤으나, CorsConfig를 이용한 인터셉터 설정에서 HTTP 메서드까지 분류해주는 기능은 없는 것으로 보임
(비슷한 질문을 한 사람이 있었고, 김영한 선생님께서 그런 방법은 없는 걸로 안다는 답변을 한 것도 봄,,😢)
---
* 다른 해결책 :  인터셉터의 preHandle 메서드에서, 경로와 메서드를 …

[Feat] POST /api/member 경로를 위한 인터셉터 설정 수정 #115

---

src/main/java/com/habitpay/habitpay/global/config/auth/interceptor/AuthorizationInterceptor.java

* #119 에서 받은 코멘트를 반영하여 수정
---
* `token`의 `isActive`값이 맞지 않아 에러가 발생한 경우 상태 코드를,
`UNAUTHORIZED`보다 더 적절한 `FORBIDDEN` 상태 코드로 변경함
* 에러 메시지의 어색한 영어 표현 수정
```java
// before
"Not an available token."
// after
"Unavailable token."
```
---
* 기타
* `handler instanceof HandlerMethod` 예외 처리 분기에서, 디버깅 겸 학습용으로 handler의 정체를 출력하는 코드 추가
```java
log.error("handler is not instanceof HandlerMethod, but {}", handler.getClass().getName());
```

[fix] 인터셉터 수정 #121

---

src/main/java/com/habitpay/habitpay/domain/ChallengeAbsenceFee/application/ChallengeAbsenceFeeSearchService.java
src/main/java/com/habitpay/habitpay/domain/challengepost/api/ChallengePostApi.java
src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostSearchService.java

* `멤버`의 `챌린지 내 포스트`를 `모아보는 기능`을 하는 서비스 메서드에 두 종류가 있었음
```java
// 내가 쓴 포스트 모아보기
public List<PostViewResponse> findChallengePostsByMe(Long challengeId, String email) { }
// email 정보를 가진 멤버가 쓴 포스트 모아보기
public List<PostViewResponse> findChallengePostsByMember(Long challengeId, String email) { }
```
* 코드 수정을 거치다보니 두 메서드의 코드가 똑같아짐.
* `findChallengePostsByMember` 이름의 메서드만 남기고 삭제하여 리팩토링 진행
---
* `enrollment`를 검색해 `벌금값`을 반환하는 메서드
* `벌금값이 0원`인 경우와, `enrollment 객체를 찾지 못한` 경우 모두 `0`을 반환했었음
* 그러나 두 경우가 구분되어야 함
```java
public int findPersonalTotalFeeOfChallenge(Member member, Challenge challenge) {
Optional<ChallengeEnrollment> optionalEnrollment = challengeEnrollmentSearchService.findByMemberAndChallenge(member, challenge);
return optionalEnrollment.map(ChallengeEnrollment::getTotalFee).orElse(-1);
} …
```

[refact] 반복되는 코드 없애기, 반환값 애매한 부분에 주석 추가 #124

---

src/main/java/com/habitpay/habitpay/domain/ChallengeAbsenceFee/application/ChallengeAbsenceFeeSearchService.java

```java
public int findPersonalTotalFeeOfChallenge(Member member, Challenge challenge) {
Optional<ChallengeEnrollment> optionalEnrollment = challengeEnrollmentSearchService.findByMemberAndChallenge(member, challenge);
return optionalEnrollment.map(ChallengeEnrollment::getTotalFee)
.orElseThrow(() -> new NoSuchElementException("This member is not in this challenge."));
}
```
* `member`와 `challenge` 데이터를 받았으나 그에 맞는 `enrollment 객체`를 찾지 못했을 경우, `예외` `던지기`로 처리

[feat] 벌금 현황 조회 서비스에서 조회에 필요한 객체를 찾지 못했을 경우, 예외를 던진다 #126

---

src/main/java/com/habitpay/habitpay/global/config/auth/CustomOAuth2UserService.java

Member 테이블에 동일한 이메일을 가진 row 가 2개 생성되는 문제를 해결했습니다.
OAuth 로그인 이후 실행 되는 `loadUser` 메서드에서 `findByEmail` 메서드에서 `orElse` 를 사용한 것이 원인이었습니다.
```diff
@Override
public OAuth2User loadUser(OAuth2UserRequest userRequest) throws OAuth2AuthenticationException {
// ...코드 생략...
String email = attributes.getEmail();
Member member = memberRepository.findByEmail(email)
+           .orElse(createMember(email));
return new CustomUserDetails(
member, oAuth2User.getAttributes()
);
}
```
이를 이해하기 위해서는 Optional 객체의 메서드 `orElse` 와 `orElseGet` 작동 방식의 차이를 이해해야 합니다. 
`orElse` 와 `orElseGet` 은 모두 Optional 객체가 null 값을 가질 때 사용하는 메서드입니다.
결론부터 이야기하면 아래와 같습니다.
**메서드가 매개변수로 전달된 경우**
- `orElse`: 매개변수로 전달된 메서드를 무조건 실행
- `orElseGet`: Optional 객체의 값이 null 인 경우에만 메서드를 실행
`orElse` 의 매개변수로 메서드가 전달되는 경우에는 Optional 객체가 null 이 아니어도 …

fix: 동일한 이메일에 대해 row 가 2개 생성되는 문제 수정 #138

---

src/main/java/com/habitpay/habitpay/domain/member/api/MemberApi.java
src/main/java/com/habitpay/habitpay/domain/member/application/MemberDeleteService.java
src/main/java/com/habitpay/habitpay/domain/member/domain/Member.java
src/main/java/com/habitpay/habitpay/domain/model/BaseTime.java

`DELETE /member` 컨트롤러에서 회원 정보 삭제 시 개인 정보만 null 로 바꾸는 soft delete 를 구현했습니다. 
컨트롤러에서 수행하던 서비스 로직을 `MemberDeleteService` 로 분리했습니다.
```java
@Service
@AllArgsConstructor
public class MemberDeleteService {
private final MemberRepository memberRepository;
private final S3FileService s3FileService;
public SuccessResponse<Long> delete(Long id) {
// TODO: 공통 예외처리 응답으로 처리하기
Member member = memberRepository.findById(id)
.filter(Member::isActive)
.orElseThrow(() -> new IllegalAccessError("이미 탈퇴한 사용자입니다."));
String imageFileName = member.getImageFileName();
log.info("[DELETE /member] imageFileName: {}", imageFileName);
if (imageFileName != null) {
s3FileService.deleteImage("profiles", imageFileName);
}
member.clear();
memberRepository.save(member);
return SuccessResponse.of("정상적으로 탈퇴되었습니다.", id);
}
} …
```

Feat/사용자 탈퇴 시 개인 정보 삭제#137

---

src/docs/asciidoc/api/member.adoc
src/test/java/com/habitpay/habitpay/domain/api/MemberApiTest.java

`DELETE /member` 컨트롤러의 테스트 코드를 작성했습니다.

Test/회원탈퇴 테스트 코드 작성#141

---

src/docs/asciidoc/api/challenge.adoc
src/main/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApi.java
src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeCreationService.java
src/main/java/com/habitpay/habitpay/domain/challenge/domain/Challenge.java
src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengeCreationRequest.java
src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengeCreationResponse.java
src/test/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApiTest.java

1. 챌린지 생성(`POST /challenges`) 컨트롤러 테스트 코드를 작성했습니다. 
2. 챌린지 생성 서비스 리팩토링을 진행했습니다.
3. 챌린지 참여 일자 변수인 `participatingDays` 의 자료형을 int 에서 byte 로 변경했습니다.

Test/챌린지 생성 컨트롤러 테스트 케이스 작성#146

---

src/docs/asciidoc/api/challenge.adoc
src/main/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApi.java
src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengePatchService.java
src/main/java/com/habitpay/habitpay/domain/challenge/domain/Challenge.java
src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengePatchRequest.java
src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengePatchResponse.java
src/test/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApiTest.java

1. 챌린지 정보 수정 컨트롤러 `PATCH /challenges/{id}` 테스트 코드를 작성했습니다. 
2. 해당 컨트롤러의 반환 자료형을 `SuccessResponse` 로 감싸주었습니다.
3. 해당 컨트롤러의 데이터에 해당하는 `ChallengePatchResponse` 클래스를 생성했습니다. (Challenge 나 ChallengeDetailsResponse 클래스를 재사용 하려고 했으나, 각 요청에 맞는 응답을 보내주는 것이 안전하다고 판단.)

Test/챌린지 정보 수정patch challengesid 테스트 코드 작성#148

---

src/docs/asciidoc/api/challengePost.adoc
src/main/java/com/habitpay/habitpay/domain/challengepost/dto/PostViewResponse.java
src/test/java/com/habitpay/habitpay/domain/api/ChallengePostApiTest.java

* `ChallengePost API`를 위한 컨트롤러의 `테스트 코드` 작성을 시작했습니다.
* 포스트를 조회하는 다음의 두 메서드를 위한 테스트 코드를 생성했습니다.
* `/GET "/api/posts/{id}"` `findPost()`
* `/GET "/api/challenges/{id}/posts"` `findChallengePosts()`
---
* `테스트 클래스`의 `설정`
* 엔티티 생성 과정에서 자동 생성되어야 할 값이 `null`로 들어오는 문제 해결 (Many thanks to joonhan)
```java
@SpringBootTest
@AutoConfigureMockMvc
public class ChallengePostApiTest extends AbstractRestDocsTests {
...
}
```
* 처음에 `@WebMvcTest(ChallengePostApi.class)` 어노테이션을 사용했습니다.
* 그러나 `Post` 객체에서 자동 생성되어야 할 `CreatedAt`의 속성값이 `null`로 나오는 문제에 직면했습니다.
* `@CreateDate` 어노테이션을 단 `CreatedAt` 속성은 실제 엔티티가 생성되고 `JPA Repository`에 저장되는 과정에서 값이 자동 생성되는데,
컨트롤러 등에만 적용되는 웹 레이어 기반인 `@WebMvcTest` 설정에서는 `DB` 컨텍스트가 아예 없기 때문이죠,,
(컨트롤러 및 필터 기반만 테스트하고, DB는 테스트하지 않기 때문에 아예 자동 생성이 이루어지지 않음)
* 그래서 DB 컨텍스트를 포함하여 테스트할 수 있도록, 테스트 …

[Test] ChallengePost API: findPost(), findChallengePosts() 메서드를 위한 테스트 코드 작성 #143

---

src/docs/asciidoc/api/challenge.adoc
src/main/java/com/habitpay/habitpay/domain/challengeenrollment/api/ChallengeEnrollmentApi.java
src/main/java/com/habitpay/habitpay/domain/challengeenrollment/application/ChallengeEnrollmentCancellationService.java
src/main/java/com/habitpay/habitpay/domain/challengeenrollment/application/ChallengeEnrollmentService.java
src/main/java/com/habitpay/habitpay/domain/challengeenrollment/domain/ChallengeEnrollment.java
src/main/java/com/habitpay/habitpay/domain/challengeenrollment/dto/ChallengeEnrollmentResponse.java
src/test/java/com/habitpay/habitpay/domain/challengeenrollment/api/ChallengeEnrollmentApiTest.java

1. 챌린지 등록 컨트롤러 (POST /challenges/{id}/enroll) 테스트 코드 작성
2. `ChallengeEnrollmentResponse` 클래스 생성
3. 챌린지 등록 컨트롤러 반환 자료형 `SuccessResponse` 클래스 적용
4. `ChallengeCancellationService` 서비스 이름 변경 -> `ChallengeEnrollmentCancellationService`
기존에 챌린지 등록 서비스 메서드에 사용했던 `@Transactional` 어노테이션을 제거했습니다.
```diff
- @Transactional
public SuccessResponse<ChallengeEnrollmentResponse> enroll(Long challengeId, Long userId) {
```
자료를 찾아보니 해당 어노테이션을 사용하는 경우는 하나의 메서드 안에서 여러 쿼리가 발생했을 때 전부 성공해야 하거나, 전부 실패해야 한다고 합니다.
예를 들면, A 가 B 에게 5만원을 송금해야 하는 경우에는 아래와 같은 순서로 쿼리가 이루어집니다.
1. A 의 잔고가 5만원 이상인지 확인 (read)
2. B 의 계좌가 입금을 받을 수 있는 상태인지 확인 (read)
3. A 의 계좌에서 5만원 인출 (update)
4. B 의 계좌에 5만원 입금 (update)
1~3번까지 작업이 성공했지만 에러가 발생해서 4번은 진행되지 않았다고 가정해봅니다.
그러면 A 의 계좌에서 돈이 나갔지만, 실제로 B 의 계좌에는 돈이 들어오지 않는 상황이 됩니다.
그래서 모든 작업이 완료될 때까지 쓰기 …

Test/챌린지 등록 post challengeidenroll 테스트 코드 작성#150

---

src/main/java/com/habitpay/habitpay/domain/challengepost/api/ChallengePostApi.java
src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostSearchService.java
src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostUtilService.java
src/main/java/com/habitpay/habitpay/domain/challengepost/dao/ChallengePostRepository.java
src/main/resources/application.yaml

* 무한 스크롤 페이지네이션 적용을 위한 백엔드 코드 초안을 작성했습니다.
* 현재 페이지네이션 코드가 적용된 메서드는,
`ChallengePost` 컨트롤러의 `getChallengePosts`, `getChallengePostsByMe`, `getChallengePostsByMember`
이렇게 n개의 포스트를 불러올 수 있는 세 개 메서드입니다.
* 페이지네이션 설정을 위한 `Pageable 객체`는, `@RequsetParam`으로 인자를 받은 후
값을 검증해 `PageRequest.of()`를 이용해 생성합니다.
---
* 인자를 받아 적용하는 방식은 세 메서드가 동일해서 아래 메서드를 대표로 설명하겠습니다.
```java
@GetMapping("/api/challenges/{id}/posts")
public SuccessResponse<List<PostViewResponse>> getChallengePosts(
@PathVariable Long id,
@RequestParam(defaultValue = DEFAULT_PAGE) int page,
@RequestParam(defaultValue = DEFAULT_SIZE) int size,
@RequestParam(defaultValue = DEFAULT_SORT) String[] sort) {
Pageable pageable = challengePostUtilService.makePageable(page, size, sort);
return SuccessResponse.of(
"", …
```

[Feat] 페이지네이션 적용을 위한 백엔드 코드 초안 작성 #160

---

src/main/java/com/habitpay/habitpay/domain/challengepost/api/ChallengePostApi.java
src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostCreationService.java
src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostDeleteService.java
src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostSearchService.java
src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostUpdateService.java
src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostUtilService.java
src/main/java/com/habitpay/habitpay/domain/refreshtoken/api/TokenApi.java
src/main/java/com/habitpay/habitpay/domain/refreshtoken/application/RefreshTokenCreationService.java

* API에서 정상응답일 경우, `SuccessResponse`로 래핑해 데이터를 리턴하게 됩니다. (`ChallengePost`, `RefreshToken` API)
* 이전에는 컨트롤러 메서드에서 래핑 과정을 수행했으나,
서비스 메서드에서 래핑 과정을 수행하는 것으로 변경했습니다.
* 가장 큰 이유는 테스트 코드에서 서비스  메서드의 반환 타입을 이용해 RestDocs 내용을 완성하는데,
`SuccessResponse`를 반영해야 프론트엔드에 정확한 API 문서를 제공할 수 있기 때문입니다.
---
```java
// before
@GetMapping("/api/posts/{id}")
public SuccessResponse<PostViewResponse> getPost(@PathVariable Long id) {
return SuccessResponse.of(
"",
challengePostSearchService.getPostViewResponseByPostId(id)
);
}
```
* 이전에는 컨트롤러 메서드에서 래핑 과정을 수행했습니다.
---
```java
// after
@GetMapping("/api/posts/{id}")
public SuccessResponse<PostViewResponse> getPost(@PathVariable Long id) {
return challengePostSearchService.getPostViewResponseByPostId(id);
}
```
* 이제는 서비스 메서드에서 래핑 과정을 수행한 후 컨트롤러에 반환합니다.
---
* 자연스레 서비스 메서드의 …

[Feat] 정상 응답을 SuccessResponse로 감싸는 과정을 컨트롤러가 아닌 서비스 메서드에서 수행하기 #162

---

src/main/java/com/habitpay/habitpay/domain/challengepost/api/ChallengePostApi.java
src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostSearchService.java
src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostUtilService.java

* `Pageable 객체`를 생성하기 위해, 이전에는 쿼리 스트링으로 `page, size` 값 등을 따로 받은 후 `PageRequest`를 이용했습니다.
* 테스트 코드 작성 용이, 가독성 높이기, JPA 공식 문서에서 `@PageDefault` 사용 등을 이유로 변경했습니다.
* 컨트롤러 메서드에서 쿼리 스트링을 인자로 받는 대신, `Pageable` 인자를 바로 받습니다.
---
```java
// before
public SuccessResponse<List<PostViewResponse>> getChallengePosts(
@PathVariable Long id,
@RequestParam(defaultValue = DEFAULT_PAGE) int page,
@RequestParam(defaultValue = DEFAULT_SIZE) int size,
@RequestParam(defaultValue = DEFAULT_SORT) String[] sort) {
Pageable pageable = challengePostUtilService.makePageable(page, size, sort);
return challengePostSearchService.findPostViewResponseListByChallengeId(id, pageable);
}
```
* 쿼리 스트링으로 인자가 많아짐에 따라 코드도 길어졌습니다.
* 쿼리 스트링 값 확인 및 `Pageable` 객체 생성을 위한 `makePageable()` 메서드가 컨트롤러단에 있었습니다.
(모든 인자를 다 넘기면 복잡해진다고 판단하여, …

[Feat] 컨트롤러 메서드에서 Pageable을 바로 인자로 받기 #165

---

src/main/java/com/habitpay/habitpay/domain/challengepost/api/ChallengePostApi.java
src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostDeleteService.java
src/test/java/com/habitpay/habitpay/domain/challegepost/api/ChallengePostApiTest.java

* ChallengePost API를 통해 포스트를 정상적으로 삭제하면 `SuccessResponse<void>` 값을 반환했습니다.
* `SuccessResponse<void>` 내의 `data` 역시 null이었습니다.
->
* null 값으로 두는 대신, 삭제된 포스트 id 데이터를 담아 `SuccessResponse<Long>` 형태로 반환하는 것으로 바꿨습니다.
```java
public SuccessResponse<Long> deletePost(Long postId, Member member) {
...
return SuccessResponse.of(
"포스트가 정상적으로 삭제되었습니다.",
postId
);
}
```
* 관련된 테스트 코드 역시 수정했습니다.

[feat] 챌린지 포스트 삭제 -> SuccessResponse data에 삭제 포스트 id 데이터 반영

---

src/docs/asciidoc/api/refreshToken.adoc
src/main/java/com/habitpay/habitpay/domain/refreshtoken/application/RefreshTokenCreationService.java
src/main/java/com/habitpay/habitpay/domain/refreshtoken/dto/CreateAccessTokenRequest.java
src/main/java/com/habitpay/habitpay/domain/refreshtoken/dto/CreateAccessTokenResponse.java
src/test/java/com/habitpay/habitpay/domain/challegepost/api/ChallengePostApiTest.java
src/test/java/com/habitpay/habitpay/domain/refreshtoken/api/RefreshTokenApiTest.java

* 리프레시 토큰 API를 위한 테스트 코드를 작성했습니다.
* 그 테스트 코드에 맞는 restDocs 문서를 작성했습니다.
* 그 과정에서, 리프레시 토큰 요청을 확인하는 메서드를 리팩토링 했습니다.
---
* Optional은 비용이 많이 든다고 알고 있어서, 요청 Json 객체의 String을 바로 확인하기 쉬운 부분의 Optional을 제거했습니다. (그런데 이거 아니면 다시 알려주십시오,, 수정하겠습니다.)
* 인증 방법을 뜻하는 `grantType` 속성의 값이 `refreshToken`과 `refresh_token`인 경우 모두 정상 처리하도록 했습니다.
(RFC 문서에는 스네이크 케이싱 기준으로 표현해서 `refresh_token`로 표현합니다.
저희는 변수명에 카멜 케이싱을 사용하기에 그 일관성을 지키면서,
일반적인 값도 받을 수 있어야 할 것만 같아 그렇게 했습니다.)
* RFC 문서에 대소문자 값을 구분한다는 이야기가 없어 `equalsIgnoreCase()` 메서드로 교체했습니다.
```java
// before
Optional<String> optionalGrantType = Optional.ofNullable(requestBody.getGrantType());
if (optionalGrantType.isEmpty() || !requestBody.getGrantType().equals("refresh_token")) {
throw new CustomJwtException(HttpStatus.BAD_REQUEST, CustomJwtErrorInfo.BAD_REQUEST, "Request …
```

[test, feat] 리프레시 토큰 테스트 코드 작성, 리프레시 토큰 작은 리팩토링 #172

---

src/main/java/com/habitpay/habitpay/domain/challenge/domain/Challenge.java
src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengeEnrolledListItemResponse.java
src/test/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApiTest.java

1. POST /challenges 컨트롤러에서 챌린지 생성 시 챌린지 총 참여 일수를 계산합니다.
2. GET /challenges/me 컨트롤러에서 챌린지 조회 시 챌린지 총 참여 일수를 포함해서 응답합니다.

feat: 챌린지 총 참여일수 추가 #175

---

src/main/java/com/habitpay/habitpay/domain/challengepost/api/ChallengePostApi.java
src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostCreationService.java
src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostDeleteService.java
src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostSearchService.java
src/main/java/com/habitpay/habitpay/domain/challengepost/dao/ChallengePostRepository.java
src/main/java/com/habitpay/habitpay/domain/challengepost/domain/ChallengePost.java
src/main/java/com/habitpay/habitpay/domain/challengepost/dto/AddPostRequest.java
src/test/java/com/habitpay/habitpay/domain/challegepost/api/ChallengePostApiTest.java

* `ChallengePost` 도메인에 `Challenge` 도메인을 외래키로 연결했습니다.
(`Challenge id` 외래키를 이용해 DB에서 빠르게 조회하기 위한 목적)
* 챌린지 내 모든 포스트를 불러오는 메서드인  `findAllChallengePostsByChallengeId`를 수정했습니다.
---
* 챌린지 포스트 도메인에 챌린지 도메인을 외래키로 연결
```java
public class ChallengePost extends BaseTime {
...
@ManyToOne
@JoinColumn(name = "challenge_id")
private Challenge challenge;
...
}
```
* 도메인 변경으로 수정이 필요한 연관 코드도 손봤습니다.
---
* 챌린지 도메인이 외래키로 연결된 덕분에, `Challenge Id` 기준으로 DB 조회가 쉬워졌습니다.
```java
public interface ChallengePostRepository extends JpaRepository<ChallengePost, Long> {
....
List<ChallengePost> findAllByChallengeId(Long challengeId, Pageable pageable);
}
```
---
* 챌린지 내 전체 포스트를 불러오는 메서드는, 위의 repository 메서드를 활용하도록 수정했습니다.
```java
public SuccessResponse<List<PostViewResponse>> findPostViewResponseListByChallengeId(Long …
```

[Feat] 챌린지 내 모든 포스트 불러오는 메서드 작성 -> ChallengePost에 Challenge 외래키 연결 #174

---

src/docs/asciidoc/api/challengePost.adoc
src/main/java/com/habitpay/habitpay/domain/challengepost/api/ChallengePostApi.java
src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostSearchService.java
src/main/java/com/habitpay/habitpay/domain/challengepost/dao/ChallengePostRepository.java
src/test/java/com/habitpay/habitpay/domain/challegepost/api/ChallengePostApiTest.java

* 챌린지 내에서 공지 포스트만 불러오는 API를 작성했습니다.
---
* 컨트롤러 메서드는 다음과 같습니다.
* `"/api/challenges/{id}/posts/announcement"` url을 사용합니다.
```java
@GetMapping("/api/challenges/{id}/posts/announcement")
public SuccessResponse<List<PostViewResponse>> getAnnouncementPosts(
@PathVariable Long id,
@PageableDefault(sort = "id", direction = Sort.Direction.DESC) Pageable pageable) {
return challengePostSearchService.findAnnouncementPostViewListByChallengeId(id, pageable);
}
```
---
* 서비스 메서드인 `findAnnouncementPostViewListByChallengeId`는
`findPostViewListByChallengeId`과 거의 동일합니다.
불러오는 레포지토리 메서드만 다릅니다.
* 레포지토리 메서드는 쿼리 메서드를 이용합니다.
```java
public interface ChallengePostRepository extends JpaRepository<ChallengePost, Long> {
...
List<ChallengePost> findAllByChallengeIdAndIsAnnouncementTrue(Long challengeId, Pageable …
```

[Feat] 챌린지 내 공지 포스트만 불러오는 메서드 및 테스트 코드 작성 #178

---

src/main/java/com/habitpay/habitpay/domain/refreshtoken/application/RefreshTokenCreationService.java
src/test/java/com/habitpay/habitpay/domain/refreshtoken/api/RefreshTokenApiTest.java

* 리프레시 토큰 API 테스트 코드에 있던 사용하지 않는 변수인 Member 객체를 삭제했습니다.
* 토큰 리프레시 요청 시 클라이언트가 요청 본문에 담아 보내는 `grant type` 값이 `refreshToken`과 동일할 때만 통과시키도록 변경했습니다.
```java
if (!grantType.equals("refreshToken")) {
throw new CustomJwtException(HttpStatus.BAD_REQUEST, CustomJwtErrorInfo.BAD_REQUEST, "취급할 수 없는 인증 방법입니다.");
```

[Feat] 피드백 반영이자 리팩토링 #180

---

src/main/java/com/habitpay/habitpay/domain/challenge/domain/Challenge.java
src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengeEnrolledListItemResponse.java
src/test/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApiTest.java

Challenge 엔티티에서 챌린지 전체 참여 일수를 의미하는 변수 `totalParticipatingDays` 의 의미를 명확하게 하기 위해 `totalParticipatingDaysCount` 로 변경했습니다. 
```java
// 변경 전
@Column(nullable = false)
private int totalParticipatingDays;
// 변경 후
@Column(nullable = false)
private int totalParticipatingDaysCount;
```

refactor: 챌린지 전체 참여 요일 수 변수명 변경 #182

---

src/main/java/com/habitpay/habitpay/domain/challengepost/api/ChallengePostApi.java

* 공지 포스트 불러오는 컨트롤러 API의 주소를 변경했습니다.
(단수 `announcement`에서 복수 `announcements`로)
* 동시에, `Announcements` 명사가 분명히 보이도록 메서드명도 수정했습니다.
```java
//before
@GetMapping("/api/challenges/{id}/posts/announcement")
public SuccessResponse<List<PostViewResponse>> getAnnouncementPosts() {...}
// after
@GetMapping("/api/challenges/{id}/posts/announcements")
public SuccessResponse<List<PostViewResponse>> getAnnouncements() {...}
```

[feat] 공지 포스트 불러오는 메서드와 url 변경 #184

---

src/docs/asciidoc/index.adoc
src/test/java/com/habitpay/habitpay/domain/challegepost/api/ChallengePostApiTest.java

* 컨트롤러 API의 바뀐 url을 반영하지 못했던 ChallengePost 테스트 코드를 수정했습니다. (단수형 -> 복수형)
```java
// before
ResultActions result = mockMvc.perform(get(".../announcement", 1L)
// after
ResultActions result = mockMvc.perform(get("/.../announcements", 1L)
```
---
* `index.adoc` 파일에 챌린지 포스트 및 리프레시 토큰 문서 파일을 추가하여, 정상적으로 RestDocs를 확인할 수 있도록 했습니다.
```java
include::api/challengePost.adoc[]
include::api/refreshToken.adoc[]
```

[Feat] 테스트 코드 수정 및 index.adoc 파일에 새 문서 추가 #186

---

src/docs/asciidoc/api/refreshToken.adoc
src/test/java/com/habitpay/habitpay/domain/refreshtoken/api/RefreshTokenApiTest.java

* `/token`로 토큰 재발급 요청 시 발생할 수 있는 `400, 401, 403 상태 코드`에 대한 테스트 코드를 작성했습니다.
* 관련된 `RestDocs` 문서를 작성했습니다.
---
* 예외를 처리하거나 다른 상태 코드를 확인하는 테스트 코드는 기존 정상 응답 테스트 코드에서 2가지만 신경 쓰면 됩니다.
* 첫 번째는 예상 응답이 `throw` 되는 `Exception`임을 밝히는 것입니다.
```java
given(refreshTokenCreationService.createNewAccessTokenAndNewRefreshToken(any(CreateAccessTokenRequest.class)))
.willThrow(new CustomJwtException(HttpStatus.BAD_REQUEST, CustomJwtErrorInfo.BAD_REQUEST, "인증 방법을 알 수 없습니다.")); 
```
* `willReturn` 대신 `WillThrow` 메서드를 사용합니다.
* 정상 응답 타압인 `SuccessResponse` 대신 `Exception`을 인자로 넣어주면 됩니다.
---
* 두 번째는 `ResultActions`의 기대값을 변경하는 것입니다.
```java
result.andExpect(status().isBadRequest())
.andDo(...);
```
* `andExpect`의 상태 코드 예상값을 `isOk()` 대신 필요한 값으로 변경하면 됩니다.
---
* 공통 예외 처리 응답 클래스가 만들어지면 그에 맞추어 변경할 예정입니다.
* 현재는 이전에 만들어 둔 기본 …

[Test] 리프레시 토큰으로 재발급 요청 시 발생하는 에러에 대한 테스트 코드 작성 #188

---

src/docs/asciidoc/api/member.adoc
src/main/java/com/habitpay/habitpay/domain/member/api/MemberApi.java
src/main/java/com/habitpay/habitpay/domain/member/application/MemberDeleteService.java
src/main/java/com/habitpay/habitpay/domain/member/application/MemberSearchService.java
src/main/java/com/habitpay/habitpay/domain/member/application/MemberUpdateService.java
src/main/java/com/habitpay/habitpay/domain/member/exception/InvalidNicknameException.java
src/main/java/com/habitpay/habitpay/global/config/jwt/JwtAuthenticationFilter.java
src/main/java/com/habitpay/habitpay/global/error/exception/ErrorCode.java
src/main/java/com/habitpay/habitpay/global/error/exception/InvalidValueException.java
src/main/java/com/habitpay/habitpay/global/response/SuccessCode.java
src/test/java/com/habitpay/habitpay/domain/member/api/MemberApiTest.java

1. 컨트롤러에서 서비스 메서드의 매개변수로 Member ID 대신 Member 객체를 넘기도록 수정했습니다.
2. Member 도메인에서 발생할 수 있는 예외처리에 대해 공통 예외처리 응답을 적용했습니다.
3. 2번에서 추가한 예외처리 응답에 대한 테스트 코드를 작성했습니다. 
4. 200 OK 응답 시 `SuccessCode` enum 에 정의한 메세지가 전송될 수 있도록 enum 클래스를 추가했습니다.

Feat/member 도메인 예외처리 공통 응답 처리#193

---

src/docs/asciidoc/api/challenge.adoc
src/main/java/com/habitpay/habitpay/domain/challengeenrollment/api/ChallengeEnrollmentApi.java
src/main/java/com/habitpay/habitpay/domain/challengeenrollment/application/ChallengeEnrollmentCancellationService.java
src/main/java/com/habitpay/habitpay/domain/challengeenrollment/application/ChallengeEnrollmentService.java
src/main/java/com/habitpay/habitpay/domain/challengeenrollment/exception/AlreadyEnrolledChallengeException.java
src/main/java/com/habitpay/habitpay/domain/challengeenrollment/exception/NotEnrolledChallengeException.java
src/main/java/com/habitpay/habitpay/global/error/exception/BadRequestException.java
src/main/java/com/habitpay/habitpay/global/error/exception/ConflictException.java
src/main/java/com/habitpay/habitpay/global/error/exception/ErrorCode.java
src/main/java/com/habitpay/habitpay/global/response/SuccessCode.java
src/main/java/com/habitpay/habitpay/global/response/SuccessResponse.java
src/test/java/com/habitpay/habitpay/domain/challengeenrollment/api/ChallengeEnrollmentApiTest.java

1. ChallengeEnrollment 도메인의 서비스 메서드에서 예외처리 시 공통 응답 클래스를 적용했습니다. 
2. ChallengeEnrollment 도메인의 예외처리에 대한 테스트 코드를 작성했습니다.
3. DELETE 작업 수행 시 `SuccessResponse` 의 data 에 null 을 넣을 수 있도록 수정했습니다. 
DELETE 작업 수행 시에는 별도의 정보를 넘겨줄 필요는 없다고 판단해서 `data` 필드에 null 을 넘겨주었습니다.
`SuccessResponse` 의 제네릭으로 `Void` 클래스를 입력합니다.
```java
// ChallengeEnrollmentApi.java
@PostMapping("/challenges/{id}/cancel")
public SuccessResponse<Void> cancelChallenge(@PathVariable("id") Long id, @AuthenticationPrincipal CustomUserDetails user) {
return challengeEnrollmentCancellationService.cancel(id, user.getMember());
}
```
`SuccessResponse` 의 `of` 메서드를 `data` 필드의 값을 입력하지 않도록 오버로딩 했습니다.
```java
// SuccessResponse.java
public static <T> SuccessResponse<T> of(SuccessCode successCode) {
return SuccessResponse.<T>builder() …
```

Feat/challengeenrollment 도메인 예외처리 공통 응답 클래스 적용#197

---

src/main/java/com/habitpay/habitpay/domain/refreshtoken/application/RefreshTokenCreationService.java
src/main/java/com/habitpay/habitpay/global/config/auth/CustomOAuth2LoginSuccessHandler.java
src/main/java/com/habitpay/habitpay/global/config/jwt/TokenService.java

* 최초 로그인 시 `RefreshToken 엔티티`가 DB에 저장되지 않는 문제 발견
---
* `OAuth2` 로그인 및 최초 회원 가입을 담당하는 `CustomOAuth2LoginSuccessHandler.java`에서 메서드 변경하기
```java
// before
String refreshToken = tokenService.createRefreshToken(memberId);
// after
String refreshToken = refreshTokenCreationService.createRefreshToken(memberId);
```
* `tokenService`의 `createRefreshToken`은 token 자체를 생성해주는 메서드
* `refreshTokenCreationService`의 `createRefreshToken`은 위의 메서드를 이용해 token을 생성하고 repo에 저장까지 해주는 메서드
---
* 이름을 헷갈리게 짓고 제대로 말씀드리지 않은 제 탓입니더.. 흑
* `createRefreshToken`가 더 쓰일 일은 없지만, 혹여나 하는 마음에 token 자체 생성만 해주는 메서드의 이름을 변경했습니다..
```java
// TokenService.java
// after
public String createRefreshToken(Long id) {
// before
public String createRefreshTokenContent(Long id) {
```

[change] refreshToken 발급 메서드 변경

---

src/docs/asciidoc/api/challenge.adoc
src/main/java/com/habitpay/habitpay/domain/challengeenrollment/application/ChallengeEnrollmentCancellationService.java
src/main/java/com/habitpay/habitpay/global/error/exception/ErrorCode.java
src/test/java/com/habitpay/habitpay/domain/challengeenrollment/api/ChallengeEnrollmentApiTest.java

1. 챌린지 주최자는 본인이 생성한 챌린지의 등록 취소는 불가능하도록 수정했습니다. (`POST /challenges/{id}/cancel`)
2. 1번에서 추가한 예외처리에 대한 테스트 코드를 작성했습니다.

Feat/챌린지 주최자 등록 취소 불가 처리#199

---

src/main/java/com/habitpay/habitpay/domain/challenge/domain/Challenge.java
src/main/java/com/habitpay/habitpay/domain/challengeenrollment/application/ChallengeEnrollmentCancellationService.java
src/main/java/com/habitpay/habitpay/domain/challengeenrollment/application/ChallengeEnrollmentService.java

1. 챌린지 등록 및 취소 시 인원이 1명이 아닌 2명씩 증감하는 문제를 수정했습니다. 
2. 챌린지 등록, 챌린지 정보 수정 작업이 모두 보장되어야 하는 메서드에 트랜잭션을 적용했습니다.

Fix/챌린지 등록 시 참여 인원 계산 문제 수정#204

---

src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeDetailsService.java
src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengeDetailsResponse.java
src/main/java/com/habitpay/habitpay/domain/challengeenrollment/dao/ChallengeEnrollmentRepository.java
src/test/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApiTest.java

챌린지 상세 정보 조회 `GET /challenges/{id}` 요청 시 참여자 프로필 이미지 링크를 전송합니다.
참여자는 최대 3명만 조회합니다. 
참고로 아래의 사진에서 주황색으로 표시된 부분에 넣어줄 프로필 이미지입니다.

Feat/챌린지 상세 정보 조회 시 참여자 프로필 이미지 링크 전송#206

---

src/main/java/com/habitpay/habitpay/domain/refreshtoken/application/RefreshTokenCreationService.java
src/main/java/com/habitpay/habitpay/global/config/auth/JwtAuthenticationEntryPoint.java
src/main/java/com/habitpay/habitpay/global/config/auth/SecurityConfig.java
src/main/java/com/habitpay/habitpay/global/config/jwt/JwtAuthenticationFilter.java
src/main/java/com/habitpay/habitpay/global/config/jwt/TokenProvider.java
src/main/java/com/habitpay/habitpay/global/config/jwt/TokenService.java
src/main/resources/application-local.yaml

* 필터에서 토큰 유효성 검사(`validToken`) 시 예외가 발생할 경우를 처리합니다.
---
* `JWT 토큰 검증` 로직이 `Interceptor`에서 스프링 시큐리티 `Filter`로 이동하면서,
`CustomJwtException`이 발생할 경우 예외 처리하는 핸들러가 필요해졌습니다.
* `스프링 시큐리티`에서는 `인증 예외`를 관리하는 `AuthenticationEntryPoint`, `인가 예외`를 관리하는 `AccessDeniedHandler`를 제공합니다.
* 그 중에서 `인증 예외`를 관리하는 `AuthenticationEntryPoint`를 활용했습니다.
---
```java
// SecurityConfig.java
SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
...
.authorizeHttpRequests((authorizeRequests ->
authorizeRequests
.requestMatchers("/oauth2/**").permitAll()
.requestMatchers("/token").permitAll()
...
http.exceptionHandling((handler) ->
handler.authenticationEntryPoint(jwtAuthenticationEntryPoint));
...
}
```
* `http.exceptionHandling` 설정을 통해 직접 만든 `jwtAuthenticationEntryPoint` 객체를 인증 예외 핸들러로 넣었습니다.
* OAuth2 …

[Feat] 필터에서 발생한 JWT 예외 처리하기 #202

---

src/docs/asciidoc/api/challenge.adoc
src/main/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApi.java
src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeDeleteService.java
src/main/java/com/habitpay/habitpay/domain/challenge/domain/Challenge.java
src/main/java/com/habitpay/habitpay/global/error/exception/ErrorCode.java
src/main/java/com/habitpay/habitpay/global/response/SuccessCode.java
src/test/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApiTest.java

1. 챌린지 시작 전 챌린지를 삭제할 수 있는 `DELETE /challenges/{id}` 컨트롤러를 추가했습니다.
2. 1번에서 추가한 컨트롤러의 테스트 코드를 작성했습니다. 
`Challenge` 삭제 시 해당하는 `Challenge` 의 `ChallengeEnrollment` 를 모두 삭제하기 위해 양방향 연결을 해주었습니다.
`@OneToMany` 의 매개변수로 `mappedBy = "challenge", cascade = CascadeType.REMOVE` 를 넘겨줍니다. 
그리고 자료형은 `List` 로 선언하고, 빈 ArrayList 를 선언해서 NPE(Null Pointer Exception) 을 방지합니다. 
```diff
@Table(name = "challenge")
public class Challenge extends BaseTime {
@Id
@GeneratedValue(strategy = GenerationType.IDENTITY)
private Long id;
@JoinColumn(name = "member_id")
private Member host;
+   @OneToMany(mappedBy = "challenge", cascade = CascadeType.REMOVE)
+   List<ChallengeEnrollment> challengeEnrollmentList = new ArrayList<>();
```

Feat/챌린지 시작 전 챌린지 삭제 기능 추가#208

---

src/main/java/com/habitpay/habitpay/global/error/exception/ErrorCode.java
src/test/java/com/habitpay/habitpay/domain/challegepost/api/ChallengePostApiTest.java

* 이전 브랜치 풀리퀘에서 conflict를 처리하던 중 `ErrorCode` 객체 내의 `;` 위치를 잘못 수정했어서,
다시 바로잡았습니다.
* `RestDocs` 문서에 반영되는 문구를 수정했습니다.
---
```java
// before
NOT_ALLOWED_TO_DELETE_CHALLENGE(HttpStatus..., "...");
// after
NOT_ALLOWED_TO_DELETE_CHALLENGE(HttpStatus..., "...."),
```
* 다음에도 Enum이 이어지는데 `;`를 그대로 써서 `ErrorCode`가 제대로 작동하지 않았습니다.
* 작동하도록 `,`를 다시 넣어 수정했습니다.
---
* `RestDocs`는 `request-fields`, `response-fields`의 요소 데이터 타입을 파악해 자동으로 문서를 만들어줍니다.
* 일반적인 객체의 경우 간단합니다.
```java
// ex (예시를 위해 대충 만들었읍니다,,)
ResponseDTO {
Long id,
String content,
List<ResponseDTO> dtoList;
}
// test code ex
...
fieldWithPath(data.id).description("..."),
fieldWithPath(data.content).description("..."),
fieldWithPath(data.dtoList).description("..."),
fieldWithPath(data.dtoList[].id).description("..."), …
```

test/ 배열 속성의 데이터 타입을 추가 작성, fix/ ErrorCode 파일의 코드 종료문 위치 수정 #214

---

src/main/java/com/habitpay/habitpay/domain/challengeenrollment/domain/ChallengeEnrollment.java
src/main/java/com/habitpay/habitpay/domain/challengeparticipationrecord/application/ChallengeParticipationRecordCreationService.java
src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostCreationService.java
src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostUtilService.java

* `ChallengeEnrollment` 엔티티에는 챌린지 내 참여 성공 횟수를 기록하는 `successCount` 속성이 있습니다.
```java
@Table(name = "challenge_enrollment")
public class ChallengeEnrollment {
...
@Column(nullable = false)
private int successCount;
...
}
```
* 챌린지 내 참여 성공 시 기록을 위한 `ChallengeParticipationRecord`가 생성되는데
이는 `enrollment` 내 `successCount`의 수와 동일해야 하므로,
`record` 엔티티 객체가 생성 및 저장될 때 `successCount`의 횟수를 `1`씩 증가시켜 정합성을 맞추는 로직을 추가했습니다.
---
* `enrollment` 엔티티 내에 `record 객체`를 받으면 `successCount`를 증가시키는 메서드를 추가했습니다.
```java
// ChallengeEnrollment.java
public void plusSuccessCountWithParticipationRecord(ChallengeParticipationRecord record) {
if (this.equals(record.getChallengeEnrollment())) {
++this.successCount;
}
}
```
* `record`의 `소속 enrollment`와 동일하면 `successCount`가 `1` 증가합니다.
---
* …

[Feat] 챌린지 참여 기록이 생성되면, enrollment 엔티티의 successCount의 횟수를 증가시킵니다.#211

---

src/main/java/com/habitpay/habitpay/domain/challengepost/api/ChallengePostApi.java
src/main/java/com/habitpay/habitpay/domain/refreshtoken/api/TokenApi.java
src/main/java/com/habitpay/habitpay/global/config/auth/SecurityConfig.java
src/test/java/com/habitpay/habitpay/domain/refreshtoken/api/RefreshTokenApiTest.java

* `@RequestMapping` 이용하여 반복되는 api 경로를 정리했습니다.
* 리프레시 토큰 요청 url에 `/api`를 추가하고 관련 코드를 수정했습니다.

[feat] 컨트롤러 api  정리 #221

---

src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostCreationService.java
src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostUpdateService.java
src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostUtilService.java
src/main/java/com/habitpay/habitpay/global/error/exception/ErrorCode.java

* `챌린지 시작 ~ 챌린지 종료 후 정산 타임` 기한을 챌린지 유효 기간으로 보고,
챌린지 유효 기간 이내에만 포스트 생성 및 수정이 가능하도록 수정했습니다.
---
* 챌린지 유효 기간 여부를 확인하는 메서드를 만들었습니다.
```java
// ChallengePostUtilService.java
public boolean isChallengePeriodForPost(Challenge challenge) {
ZonedDateTime now = ZonedDateTime.now();
return now.isAfter(challenge.getStartDate()) && !challenge.isPaidAll();
}
```
---
* 챌린지 포스트를 생성 혹은 수정하기 전에 위의 메서드로 검사하고,
검사  결과가 `false`라면 예외를 던집니다.
```java
throw new ForbiddenException(ErrorCode.POST_EDITABLE_ONLY_WITHIN_CHALLENGE_PERIOD);
```
```java
// ErrorCode
POST_EDITABLE_ONLY_WITHIN_CHALLENGE_PERIOD(HttpStatus.FORBIDDEN, "챌린지 유효 기간에만 포스트를 작성 및 수정할 수 있습니다."),
```

[feat] 챌린지 유효 기간이 아닐 시 포스트 생성 및 수정 불가 #224

---

src/main/java/com/habitpay/habitpay/domain/member/application/MemberDeleteService.java
src/main/java/com/habitpay/habitpay/domain/refreshtoken/application/RefreshTokenCreationService.java
src/main/java/com/habitpay/habitpay/domain/refreshtoken/application/RefreshTokenDeleteService.java
src/main/java/com/habitpay/habitpay/domain/refreshtoken/dao/RefreshTokenRepository.java
src/main/java/com/habitpay/habitpay/domain/refreshtoken/domain/RefreshToken.java

* 회원 탈퇴 시, 회원의 리프레시 토큰 정보를 담고 있는 RefreshTokenRepository의 컬럼도 삭제합니다.
---
*`Member` 객체를 받으면 그에 대응하는 `RefreshToken`을 삭제하는 메서드를 만들었습니다.
```java
// RefreshTokenDeleteService.java
public void delete(Member member) {
Optional<RefreshToken> optionalRefreshToken = refreshTokenRepository.findByMember(member);
optionalRefreshToken.ifPresent(refreshTokenRepository::delete);
}
```
---
* 멤버를 탈퇴할 경우 처리하는 메서드에 위의 메서드를 추가했습니다.
```java
// MemberDeleteService.java
@Transactional
public SuccessResponse<Long> delete(Member member) {
...
refreshTokenDeleteService.delete(member);
member.clear();
memberRepository.save(member);
return ..;
}
```
* 삭제는 한 단위로 진행되어야 해서 @Transactional 어노테이션을 추가했습니다.
---
* 메서드 호출을 줄이는 방향으로 작은 리팩토링을 진행했습니다.
---
* 확실한 양방향 삭제를 위해 `cascade = CascadeType.REMOVE`를 염두에 두고 계셨을 수도 있겠다는 생각이 …

[Feat] 회원 탈퇴 시 리프레시 토큰도 레포지토리에서 삭제 #226

---

src/docs/asciidoc/api/refreshToken.adoc
src/main/java/com/habitpay/habitpay/domain/member/domain/Member.java
src/main/java/com/habitpay/habitpay/domain/refreshtoken/api/TokenApi.java
src/main/java/com/habitpay/habitpay/domain/refreshtoken/application/RefreshTokenCreationService.java
src/main/java/com/habitpay/habitpay/domain/refreshtoken/application/RefreshTokenUtilService.java
src/main/java/com/habitpay/habitpay/domain/refreshtoken/dto/CreateAccessTokenResponse.java
src/main/java/com/habitpay/habitpay/global/config/auth/CustomOAuth2LoginSuccessHandler.java
src/main/java/com/habitpay/habitpay/global/config/jwt/TokenProvider.java
src/main/java/com/habitpay/habitpay/global/config/jwt/TokenService.java
src/main/java/com/habitpay/habitpay/global/error/exception/ErrorCode.java
src/main/java/com/habitpay/habitpay/global/handler/GlobalExceptionHandler.java
src/main/java/com/habitpay/habitpay/global/util/CookieUtil.java
src/test/java/com/habitpay/habitpay/domain/refreshtoken/api/RefreshTokenApiTest.java

* 최초 로그인 시 `리프레시 토큰`은 `쿠키`를 통해 전달됩니다.
* 그러나 `토큰 재발급 요청` 로직에는 `쿠키`가 아닌,
(예전에 만든 방식인) `요청 및 응답 본문`을 통해 `리프레시 토큰`을 주고 받는 방식이 사용되고 있었습니다.
* 이를 `쿠키`를 통해 `리프레시 토큰`을 주고 받는 로직으로 변경했습니다.
---
* `리프레시 토큰 컨트롤러` 메서드에서 `요청 본문`을 받는 대신,
`HttpServletRequest`와 `HttpServletResponse`만 인자로 받습니다.
```java
// TokenApi.java
@PostMapping("/token")
public SuccessResponse<CreateAccessTokenResponse> createNewAccessTokenAndNewRefreshToken(
HttpServletRequest request,
HttpServletResponse response) {
return refreshTokenCreationService.createNewAccessTokenAndNewRefreshToken(request, response);
}
```
* `쿠키`를 주고 받는 게 필요하기 때문에 `HttpServlet 요청 및 응답`만 있으면 됩니다.
---
* 로직을 담당하는 서비스 메서드는 다음과 같습니다.
```java
// RefreshTokenCreationService.java
public SuccessResponse<CreateAccessTokenResponse> createNewAccessTokenAndNewRefreshToken( …
```

[Feat] 토큰 재발급 시 리프레시 토큰을 쿠키로 주고 받기 #231

---

src/main/java/com/habitpay/habitpay/global/util/CookieUtil.java

* 리프레시 토큰 값을 관리하는 쿠키의 이름을 `refresh`에서 `refresh_token`으로 변경했습니다.
* 응답으로 보낼 쿠키를 설정할 때도, 요청으로 온 쿠키를 확인할 때도 적용됩니다.
---
* HTTP 쿠키 이름에서는 스네이크 케이싱이 관습인 것 같아 `refresh_token`으로 우선 설정했습니다.
* 변경 가능성 및 프론트엔드에는 아직 변경사항이 전달되지 않아서, 확인 및 변경 후 머지하면 될 듯 합니다.

[feat] 토큰 리프레시를 위한 쿠키의 키값 이름을 refresh_token으로 변경 #236

---

.github/workflows/deploy.yaml
deploy.sh
src/main/java/com/habitpay/habitpay/domain/challengeabsencefee/application/ChallengeAbsenceFeeSearchService.java
src/main/java/com/habitpay/habitpay/domain/challengeabsencefee/dto/FeeStatusResponse.java
src/main/java/com/habitpay/habitpay/domain/challengeabsencefee/dto/MemberFee.java
src/main/java/com/habitpay/habitpay/domain/challengeabsencefee/dto/MemberFeeView.java
src/main/java/com/habitpay/habitpay/domain/challengeenrollment/dao/ChallengeEnrollmentRepository.java
src/test/java/com/habitpay/habitpay/domain/challengeabsencefee/api/ChallengeAbsenceFeeApiTest.java

`GET /challenges/[challenge-id]/fee` 기존 응답은 아래와 같았습니다.
```json
{
"totalFee": 3000,
"myFee": 1000,
"memberFeeList": [
{
"nickname": "hello",
"totalFee": 1000,
"completionRate": 70,
}
]
}
```
벌금 조회를 요청한 유저를 표시하기 위해 아래와 같이 `isMe` 속성을 추가합니다.
```json
{
"totalFee": 3000,
"myFee": 1000,
"memberFeeList": [
{
"nickname": "hello",
"totalFee": 1000,
"completionRate": 70,
"isMe": true
}
]
}
```

Feat/챌린지 벌금 조회 시 본인 확인 속성 추가#248

---

src/docs/asciidoc/api/challenge.adoc
src/main/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApi.java
src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeSearchService.java
src/main/java/com/habitpay/habitpay/domain/challenge/dao/ChallengeRepository.java
src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengePageResponse.java
src/main/java/com/habitpay/habitpay/global/response/PageResponse.java
src/main/resources/application.yaml
src/test/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApiTest.java

1. 챌린지 전체 목록을 조회하는 API `GET /api/challenges?page={pageNo}` 를 구현했습니다.
2. 1번 API 테스트 코드를 작성했습니다.
챌린지 전체 목록 조회 시, 프론트에서 Pagination 을 이용해서 보여줄 수 있도록 했습니다.
```java
// ChallengeSearchService.java
public SuccessResponse<PageResponse<ChallengePageResponse>> getChallengePage(Pageable pageable) {
Page<ChallengePageResponse> challengePage = challengeRepository.findAll(pageable)
.map(challenge -> {
String hostProfileImage = Optional.ofNullable(challenge.getHost().getImageFileName())
.map((imageFilename) -> s3FileService.getGetPreSignedUrl("profiles", imageFilename))
.orElse("");
return ChallengePageResponse.of(challenge, hostProfileImage);
});
return SuccessResponse.of(SuccessCode.NO_MESSAGE, PageResponse.from(challengePage));
}
```
Slice 와 유사하게 repository 에서 매개변수로 `Pageable` 객체를 전달하면 `Page` 객체가 …

Feat/챌린지 전체 목록 조회 기능 구현#252

---

src/docs/asciidoc/api/challenge.adoc
src/main/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApi.java
src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeDetailsService.java
src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengeDatesResponse.java
src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengeFeePerAbsenceResponse.java
src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengeParticipatingDaysResponse.java
src/test/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApiTest.java

챌린지 개별 정보를 조회할 수 있는 API 와 테스트 코드를 구현했습니다.
1. 챌린지 1회 실패당 벌금(`feePerAbsence`) 조회 API
2. 챌린지 진행 기간(`startDate`, `endDate`) 조회 API
3. 챌린지 참여 요일(`participatingDays`) 조회 API
- 참여 요일은 `["월", "화"]` 와 같이 `String[]` 자료형으로 반환합니다.

Feat/챌린지 개별 정보 api 개발#256

---

.github/workflows/deploy.yaml

GitHub Actions 에서 AWS SSM 실행하는 부분을 개별 jobs 로 분리하고, 순서를 보장하도록 설정했습니다.

:bug: fix: AWS SSM 실행 jobs 로 분리 #258

---

src/docs/asciidoc/api/challenge.adoc
src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeCreationService.java
src/main/java/com/habitpay/habitpay/domain/challenge/exception/InvalidChallengeParticipatingDaysException.java
src/main/java/com/habitpay/habitpay/global/error/exception/ErrorCode.java
src/test/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApiTest.java

챌린지 생성 시 챌린지 진행 기간에 챌린지 참여 요일이 하나라도 포함되지 않은 경우 챌린지 생성을 하지 못하도록 예외처리를 추가했습니다.

Feat/챌린지 생성 시 참여 요일 검증 추가#261

---

src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeDetailsService.java
src/main/java/com/habitpay/habitpay/domain/challenge/domain/Challenge.java
src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengeDetailsResponse.java
src/main/resources/application-dev.yaml
src/test/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApiTest.java

* 챌린지 상세 페이지(`http://localhost:3000/challenges/{id}/main`)에서 `챌린지 전체 벌금` 데이터를 아직 확인할 수 없었습니다.
* 이를 해결하기 위해 `ChallengeDetailsResponse DTO`에 `챌린지 전체 벌금` 속성을 추가했습니다.
(챌린지 상세 페이지에 데이터를 보내는 DTO)
---
* `ChallengeDetailsResponse DTO`에 전체 벌금(`totalAbsenceFee`) 속성 추가
```java
public class ChallengeDetailsResponse {
...
private int totalAbsenceFee;
...
}
```
---
* `getChallengeDetails` 메서드에 로직 추가
* `챌린지 상세 페이지` 요청 시 작동하는 메서드
* `ChallengeDetailsResponse DTO`의 값을 채우는 실질적인 메서드
```java
public SuccessResponse<ChallengeDetailsResponse> getChallengeDetails(Long challengeId, Member member) {
...
List<ChallengeEnrollment> enrollmentList = challengeEnrollmentRepository.findAllByChallenge(challenge);
int totalAbsenceFee = enrollmentList
.stream()
.mapToInt(enrollment -> …
```

[feat] 챌린지 상세 페이지에서 챌린지 전체 벌금값 확인하기 #265

---

src/docs/asciidoc/api/challenge.adoc
src/main/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApi.java
src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeDetailsService.java
src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengeTotalAbsenceFeeResponse.java
src/test/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApiTest.java

* 챌린지 개별 데이터 조회를 위한 API에, `챌린지 내 전체 벌금 조회` 메세드를 추가했습니다.
---
* `TotalAbsenceFee`를 조회하는 컨트롤러 메서드입니다.
```java
// ChallengeApi.java
@GetMapping("/challenges/{id}/fees/absence/total")
public SuccessResponse<ChallengeTotalAbsenceFeeResponse> getChallengeTotalAbsenceFee(@PathVariable("id") Long id) {
return challengeDetailsService.getChallengeTotalAbsenceFee(id);
}
```
---
* `TotalAbsenceFee`를 위한 DTO입니다.
```java
public class ChallengeTotalAbsenceFeeResponse {
private int totalAbsenceFee;
public static ChallengeTotalAbsenceFeeResponse from(int totalAbsenceFee) {
return ChallengeTotalAbsenceFeeResponse
.builder()
.totalAbsenceFee(totalAbsenceFee)
.build();
}
}
```
* 추가 로직이 필요하여 `Challenge`를 바로 인자로 받진 않지만,
비슷한 특성의 메서드로 보고 `from` 이름을 그대로 참고했습니다.
---
* `TotalAbsenceFee`값을 구하는 서비스 메서드입니다.
```java
// …
```

[Feat] 챌린지 개별 데이터 조회 api : 전체 벌금 조회 추가 #268

---

src/main/resources/db/migration/V202410162038__Add_totalAbsenceFee_in_challenge.sql

운영 서버에는 `absenceTotalFee` 가 삭제되지 않아서 Flyway DB 마이그레이션이 작동하지 않았습니다. 
즉, `absenceTotalFee` 컬럼을 생성하려는 SQL 은 이미 존재하는 컬럼에 대해서 실행되었기 때문에 오류가 발생했습니다.
```bash
Caused by: org.flywaydb.core.internal.sqlscript.FlywaySqlScriptException: Migration V202410162038__Add_totalAbsenceFee_in_challenge.sql failed
--------------------------------------------------------------------
SQL State  : 42701
Error Code : 0
Message    : ERROR: column "total_absence_fee" of relation "challenge" already exists
Location   : db/migration/V202410162038__Add_totalAbsenceFee_in_challenge.sql (/usr/app/nested:/usr/app/app.jar/!BOOT-INF/classes/!/db/migration/V202410162038__Add_totalAbsenceFee_in_challenge.sql)
Line       : 1
Statement  : ALTER TABLE challenge
ADD total_absence_fee integer
at …
```

remove: absenceTotalFee 컬럼 생성 sql 파일 삭제 #278

---

src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeDetailsService.java
src/main/java/com/habitpay/habitpay/domain/challenge/domain/Challenge.java
src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengeDetailsResponse.java
src/main/java/com/habitpay/habitpay/domain/challengeabsencefee/application/ChallengeAbsenceFeeSearchService.java
src/main/java/com/habitpay/habitpay/domain/challengescheduler/application/ChallengeSchedulerService.java
src/main/java/com/habitpay/habitpay/domain/challengescheduler/application/SchedulerTaskHelperService.java

* `Challenge` 엔티티 클래스에 전체 벌금 총합을 가리키는 `totalAbsenceFee` 필드가 추가되며 코드 수정이 필요했습니다.
* 우선 `Challenge 객체`의 전체 벌금 총합을 구하는 로직을 변경했습니다.
* 챌린지 참가자가 참여 실패할 경우 개인 벌금만 수정하던 로직에 더해,
챌린지 내 필드인 `totalAbsenceFee`에도 벌금을 더하는 코드를 추가했습니다.
---
* `챌린지 벌금 현황 데이터`를 가공하는 서비스 메서드에서,
`챌린지 전체 벌금 총합`은 챌린지 내 필드인 `totalAbsenceFee`값을 `getter`로 가져오도록 했습니다.
(이전 : 챌린지 내 참가자들의 개인 벌금을 합하여 구했음)
```java
// ChallengeAbsenceFeeSearchService.java
public SuccessResponse<FeeStatusResponse> makeMemberFeeDataListOfChallenge(Long challengeId, Member member) {
...
FeeStatusResponse feeStatusResponse = FeeStatusResponse.builder()
.totalFee(challenge.getTotalAbsenceFee())
...
.build();
...
}
```
---
* `챌린지 전체 벌금 총합` 데이터가 필요한 `ChallengeDetailsResponse` DTO의 생성 메서드도 수정했습니다.
```java
// ChallengeDetailsResponse.java
public static …
```

[Feat] Challenge 엔티티 클래스에 totalAbsenceFee 필드 추가에 따른 코드 수정 #275

---

src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeDetailsService.java
src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeSearchService.java
src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengeDetailsResponse.java
src/main/java/com/habitpay/habitpay/domain/challengeparticipationrecord/application/ChallengeParticipationRecordUtilService.java
src/test/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApiTest.java

* 챌린지 상세 페이지를 위한 API인 `GET` `/api/challenges/{id}`를 통해 접속하면,
웹 뷰에 `금일 챌린지에 참여했는지 여부`를 알리는 문구가 있습니다.
* 현재는 다음과 같은 문구로 고정되어 있습니다.
```java
오늘은 챌린지에 참여하지 않으셨습니다!
챌린지 인증 글을 작성해주세요.
```
* 이 문구를 상황에 맞게 바꿀 수 있도록, 해당 API 반환 데이터에 `'오늘 참여 여부'` 관련 정보를 추가합니다.
---
* 챌린지 상세 페이지를 위한 DTO인 `ChallengeDetailsResponse`에  `isTodayParticipatingDay`, `isParticipatedToday` 속성을 추가했습니다.
```java
// ChallengeDetailsResponse.java
public class ChallengeDetailsResponse {
...
private Boolean isTodayParticipatingDay;
private Boolean isParticipatedToday;
...
}
```
* `ChallengeDetailsResponse` 생성 메서드인 `of`에도 해당 속성을 추가했습니다.
```java
public static ChallengeDetailsResponse of(Member member, Challenge challenge, List<String> enrolledMembersProfileImageList, Boolean isMemberEnrolledInChallenge, Boolean isParticipatedToday) { …
```

[Feat] 챌린지 상세 페이지 API 데이터에 '오늘 참여 여부' 추가 #283

---

src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengeDetailsResponse.java
src/test/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApiTest.java

* 이전 커밋을 푸쉬 안 하고 누락한 채 풀리퀘를 하여서 수습했습니다.
```java
// ChallengeDetailsResponse.java
public class ChallengeDetailsResponse {
...
private Boolean isTodayParticipatingDay;
...
}
```
* 위의 속성을 추가하고 관련 코드와 테스트 코드를 수정했습니다.

[add] 누락 커밋 추가 : 챌린지 디테일 DTO에 '오늘이 참여일인지 여부' 속성 추가 #286

---

src/main/java/com/habitpay/habitpay/domain/challengeparticipationrecord/application/ChallengeParticipationRecordSearchService.java
src/main/java/com/habitpay/habitpay/domain/challengescheduler/application/ChallengeSchedulerService.java
src/main/java/com/habitpay/habitpay/domain/challengescheduler/application/SchedulerTaskHelperService.java

* 스케쥴러 서비스 메서드에 타임존 컨터버 메서드(`ETC` -> `Asia/Seoul`)를 적용했습니다.
* `요일 비교`나 `서울 시간대 기준 작업`이 필요한 경우에 한해서입니다.
---
* 시간대를 수동으로 설정하던 부분을 메서드 사용으로 바꿨습니다.
```java
ZonedDateTime startOfToday = ZonedDateTime.now().withZoneSameInstant(ZoneId.of("Asia/Seoul")).with(LocalTime.MIDNIGHT);
=>
ZonedDateTime startOfToday = TimeZoneConverter.convertEtcToLocalTimeZone(ZonedDateTime.now()).with(LocalTime.MIDNIGHT);
```
* DB에 데이터 조회가 필요한 경우에 데이터를 서울 시간대로 변경하였습니다.
```java
ZonedDateTime yesterday = ZonedDateTime.now().minusDays(1).with(LocalTime.MIDNIGHT);
=>
ZonedDateTime today = TimeZoneConverter.convertEtcToLocalTimeZone(ZonedDateTime.now());
ZonedDateTime yesterday = today.minusDays(1).with(LocalTime.MIDNIGHT);
```

[feat] 스케쥴러 서비스 메서드에 타임존 컨터버 적용하기 #281

---

src/main/java/com/habitpay/habitpay/domain/challengescheduler/application/SchedulerTaskHelperService.java

* `스케쥴러 서비스`에 매일 챌린지 참여 여부를 검사하고 벌금을 집계하는 메서드가 있습니다.
* 핵심 로직은 `checkFailedParticipation`라는 메서드가 담당하고 있습니다.
* 이 메서드에서 `totalAbsenceFee`를 제대로 집계하지 않는 문제가 있어 코드를 수정했습니다.
* 또한 Challenge 목록을 순회할 때 복잡도를 줄이기 위해, `List` 대신 `HashMap`을 채택했습니다.
---
```java
// SchedulerTaskHelperService.java
public void checkFailedParticipation(List<Challenge> challengeList, ZonedDateTime yesterday) {
HashMap<Challenge, Integer> challengeFailureCountMap = new HashMap<>();
...
challengeParticipationRecordSearchService.findByChallengesAndTargetDate(challengeList, yesterday)
.forEach(record -> {
if (!record.existsChallengePost()) {
...
Challenge challenge = record.getChallenge();
setFailureCountInChallengeMap(challengeFailureCountMap, challenge);
...
}
});
List<Challenge> feeAddedChallengeList = …
```

[fix] 스케쥴러 서비스 메서드 : 매일 챌린지 참여 검사 시, totalAbsenceFee가 제대로 합산되지 않는 로직 수정 #292

---

src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeRecordsService.java
src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengeRecords.java
src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengeRecordsResponse.java
src/test/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApiTest.java

* 챌린지 별 참여 기록 데이터를 생성하는 `ChallengeRecordsService` 클래스를 중심으로 서비스 메서드는 비즈니스 로직에 집중하도록 리팩토링했습니다.
---
* `챌린지 별 참여 기록` 데이터에는 `성공 날짜 목록`, `실패 날짜 목록`, `다가오는 날짜 목록`의 세 요소가 존재합니다.
* 이 세 요소를 관리하기 위한 `ChallengeRecords DTO`가 추가됐습니다.
```java
// ChallengeRecords.java
public class ChallengeRecords {
private List<LocalDate> successDayList;
private List<LocalDate> failureDayList;
private List<LocalDate> upcomingDayList;
public ChallengeRecords() {
successDayList = new ArrayList<>();
failureDayList = new ArrayList<>();
upcomingDayList = new ArrayList<>();
}
public void addSuccessDay(LocalDate date) {
successDayList.add(date);
}
public void addFailureDay(LocalDate date) {
failureDayList.add(date);
}
public void addUpcomingDay(LocalDate date) {
upcomingDayList.add(date);
}
}
```
---
* 위의 DTO를 활용해 비즈니스 로직을 …

[refactor] 챌린지 참여 기록을 위한 메서드 리팩토링 #294

---

src/docs/asciidoc/api/challenge.adoc
src/docs/asciidoc/api/challengeEnrollment.adoc
src/docs/asciidoc/api/challengePost.adoc
src/docs/asciidoc/index.adoc
src/main/java/com/habitpay/habitpay/domain/challenge/domain/Challenge.java
src/main/java/com/habitpay/habitpay/domain/challengeenrollment/api/ChallengeEnrollmentApi.java
src/main/java/com/habitpay/habitpay/domain/challengeenrollment/application/ChallengeEnrollmentCancellationService.java
src/main/java/com/habitpay/habitpay/domain/challengeenrollment/exception/AlreadyGivenUpChallengeException.java
src/main/java/com/habitpay/habitpay/domain/challengeparticipationrecord/dao/ChallengeParticipationRecordRepository.java
src/main/java/com/habitpay/habitpay/domain/challengepost/api/ChallengePostApi.java
src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostCreationService.java
src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostDeleteService.java
src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostUpdateService.java
src/main/java/com/habitpay/habitpay/global/error/exception/ErrorCode.java
src/main/java/com/habitpay/habitpay/global/handler/GlobalExceptionHandler.java
src/main/java/com/habitpay/habitpay/global/response/SuccessCode.java
src/test/java/com/habitpay/habitpay/domain/challegepost/api/ChallengePostApiTest.java
src/test/java/com/habitpay/habitpay/domain/challengeenrollment/api/ChallengeEnrollmentApiTest.java

챌린지 시작 이후 중도 포기를 위한 API 를 구현했습니다.
중도 포기는 챌린지 등록 관련 로직이라 생각하여 `ChallengeEnrollment` 도메인에 챌린지 중도 포기 컨트롤러를 추가했습니다.
```java
@PostMapping("/challenges/{id}/give-up")
public SuccessResponse<Void> giveUpChallenge(@PathVariable("id") Long id, @AuthenticationPrincipal CustomUserDetails user) {
return challengeEnrollmentCancellationService.giveUp(id, user.getMember());
}
```
챌린지 중도 포기 시, DB 에서 수행되는 작업은 다음과 같이 3가지 입니다. 
1. `ChallengeEnrollment` 엔티티의 `isGivenUp` 을 true 로 설정합니다.
2. `Challenge` 엔티티의 전체 참여자 수를 1만큼 감소시킵니다.
3. `challenge_participation_record` 테이블에서 오늘을 포함한 이후 날짜에 해당하는 모든 참여 기록을 삭제합니다.
```java
@Transactional
public SuccessResponse<Void> giveUp(Long challengeId, Member member) {
Challenge challenge = challengeSearchService.getChallengeById(challengeId);
ChallengeEnrollment …
```

[feat] 챌린지 중도포기 api 구현#300

---

src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeDetailsService.java
src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeSearchService.java
src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengeDetailsResponse.java
src/test/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApiTest.java

챌린지 상세 정보 조회 컨트롤러 `GET /challenges/{id}` 의 response DTO 에 `중도 포기 여부`를 보여주는 `isGivenUp` 필드를 추가했습니다.
그리고 가독성 향상을 위해 일부 메서드는 리팩토링 했습니다.
`ChallengeDetailsResponse` DTO 에 `isGivenUp` 필드를 추가했습니다.
```java
@Getter
@Builder
public class ChallengeDetailsResponse {
// ...중략
private Boolean isHost;
private Boolean isMemberEnrolledInChallenge;
private Boolean isGivenUp; // 추가한 필드
}
```
추가된 필드에 맞게 테스트 코드를 수정했습니다.
서비스 메서드의 가독성을 높이기 위해 별도의 메서드로 분리하는 작업을 했습니다.

[feat] 챌린지 정보 조회 시 사용자의 중도 포기 여부 추가#302

---

src/main/java/com/habitpay/habitpay/domain/challengescheduler/application/SchedulerTaskHelperService.java

* `SchedulerTaskHelperService` 클래스의 `checkfailedparticipation` 메서드를 리팩토링했습니다.
* 내용은 #293 의 코멘트를 반영했습니다. 리팩토링 제안 감사드립니다.
---
```java
* 챌린지 별 실패 횟수를 관리하기 위해 `setFailureCountInChallengeMap`이라는 커스텀 setter 메서드를 만들어 사용했었음
=> `HashMap`의 `getOrDefault()`이라는 기본 메서드를 이용하도록 리팩토링
```
```java
* `HashMap`을 순회하기 위해 `Entry`를 대상으로 하는 `for문` 이용했었음
=>`key`와 `value`값만 이용해 `forEach문`을 이용하도록 리팩토링
```

[refactor] SchedulerTaskHelperService 클래스의 checkfailedparticipation 리팩토링 #304

---

src/main/java/com/habitpay/habitpay/domain/challenge/domain/Challenge.java

* 문제 파악을 위한 디버깅 목적의 로그를 추가했습니다.
* 문제가 해결되면 삭제할 예정입니다(혹은 더 정제해서 아예 `log.info()`로 변경).
* 해결하고자 하는 문제는 운영 서버에서 챌린지 생성 시 DB에 `records`가 적절하게 생성되지 않는 문제입니다.
(여러 개의 record가 생성되어야 함에도, 챌린지 당 1개씩만 생성되는 문제)
---
```java
// domain/Challenge
public List<ZonedDateTime> getParticipationDates() {
...
ZonedDateTime startDateInLocal = TimeZoneConverter.convertEtcToLocalTimeZone(this.getStartDate());
ZonedDateTime targetDate = startDateInLocal.with(TemporalAdjusters.nextOrSame(targetDay));
// todo : 해결되면 삭제
log.debug("challenge.getId() : {}", this.getId());
log.debug("[startDate(UTC), startDate(KST)]");
log.debug("{}, {}", this.getStartDate(), startDateInLocal);
log.debug("first targetDate : {}", targetDate);
ZonedDateTime endDateInLocal = TimeZoneConverter.convertEtcToLocalTimeZone(this.getEndDate()); …
```

[Debug] 디버깅 목적의 로그 추가 : 운영 서버에서 챌린지 생성 시 records가 적절하게 생성되지 않는 문제 #308

---

src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeCreationService.java
src/main/java/com/habitpay/habitpay/domain/challenge/dao/ChallengeRepository.java
src/main/java/com/habitpay/habitpay/domain/challenge/domain/Challenge.java
src/main/java/com/habitpay/habitpay/domain/challengescheduler/application/ChallengeSchedulerService.java
src/main/java/com/habitpay/habitpay/domain/challengescheduler/application/SchedulerTaskHelperService.java

* 이전에는 `챌린지 시작 및 종료`를 매일 자정에 한 번씩 확인했습니다.
* 이제는 `챌린지 시작 및 종료`를 매 분마다 확인해 처리합니다.
* 덕분에 `챌린지 생성` 시 입력한 `시작 및 종료 시간대`에 맞춰 작동합니다.
---
* 스케쥴러 메서드의 cron 설정을 매 분마다 작동하도록 변경했습니다.
```java
// ChallengeSchedulerService.java
@Scheduled(cron = "0 * * * * *", zone = "Asia/Seoul")
public void setChallengeForStart() {
...
}
...
@Scheduled(cron = "0 * * * * *", zone = "Asia/Seoul")
public void setChallengeForEnd() {
...
}
```
---
* 매 분 시작 및 종료하는 `챌린지`를 검색하기 위해서,
현재 시간 `분 대에 해당하는 시작과 끝 초`를 이용한 변수를 사용하도록 변경했습니다.
(이전에는 하루의 `시작(00:00)`과 `끝(23:59:999..)` 시간대를 사용했음)
```java
ZonedDateTime now = TimeZoneConverter.convertEtcToLocalTimeZone(ZonedDateTime.now());
ZonedDateTime startOfMinute = now.withSecond(0).withNano(0);
ZonedDateTime endOfMinute = now.withSecond(59).withNano(999_999_999);
...
return …
```

[feat] 챌린지 시작과 종료를 매 분마다 확인 및 처리 #310

---

src/main/java/com/habitpay/habitpay/domain/challenge/dao/ChallengeRepository.java
src/main/java/com/habitpay/habitpay/domain/challengescheduler/application/SchedulerTaskHelperService.java

* 이전에는 챌린지 시작과 종료를 매 분마다 확인하는 스케쥴러 메서드가 나노초를 기준으로 작동했습니다.
```java
// before
// SchedulerTaskHelperService.java
ZonedDateTime startOfMinute = now.withSecond(0).withNano(0);
ZonedDateTime endOfMinute = now.withSecond(59).withNano(999);
```
* 의미를 살리고 더 정확하게 작동하도록, 1분을 더하는 메서드를 사용하도록 변경했습니다.
```java
// after
// SchedulerTaskHelperService.java
ZonedDateTime startOfMinute = now.withSecond(0).withNano(0);
ZonedDateTime endOfMinute = now.plusMinutes(1).withSecond(0).withNano(0);
```
* DB 조회 메서드에서 `startOfMinute`와 `endOfMinute` 변수를 인자로 받을 때, `이상 이하` 대신 `이상 미만`을 기준으로 작동하도록 쿼리문을 붙였습니다.
```java
// ChallengeRepository.java
@Query("SELECT c FROM Challenge c WHERE :startOfMinute <= c.startDate AND c.startDate < :endOfMinute AND c.state = :state")
List<Challenge> …
```

[refact] 스케쥴러 서비스 메서드 리팩토링(코멘트 반영) #317

---

src/main/java/com/habitpay/habitpay/domain/challengepost/api/ChallengePostApi.java
src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostSearchService.java
src/main/java/com/habitpay/habitpay/global/response/SliceResponse.java
src/test/java/com/habitpay/habitpay/domain/challegepost/api/ChallengePostApiTest.java

`GET /challenges/{id}/posts`의 response가 2번째 페이지부터 반환하지 못하는 문제를 해결하기 위해 page number가 1부터 시작하도록 수정합니다.
챌린지 메인 페이지에서 스크롤을 내리면 다음 페이지 내용이 나오는 것이 아닌 첫 페이지 내용이 반복해서 표시되었습니다.
프론트에서는 `GET /challenges/{id}/posts?page=1`와 같이 page number를 1부터 요청을 하는데, 백엔드에서는 `pageable.pageNumber`의 값이 아래와 같이 0부터 시작합니다.
```json
{
"message": "",
"data": {
"content": [
{
"id": 13,
"challengeId": 6,
"content": "13",
"writer": "joonhyeok.han",
"isPostAuthor": true,
"profileUrl": "",
"isAnnouncement": false,
"createdAt": "2024-12-05T10:23:01.272858",
"photoViewList": []
},
],
"pageable": {
"pageNumber": 0, // 0부터 시작하는 페이지 번호
"pageSize": 10,
"sort": {
"sorted": true,
"unsorted": false,
"empty": false
},
"offset": 0,
"paged": true,
"unpaged": false
},
"size": 10,
"number": 0,
"sort": {
"sorted": true,
"unsorted": false, …
```

Fix/게시물 pageable response dto 1부터 반환하도록 수정#322

---

src/main/java/com/habitpay/habitpay/domain/challengeenrollment/application/ChallengeEnrollmentCancellationService.java
src/main/java/com/habitpay/habitpay/domain/challengeenrollment/domain/ChallengeEnrollment.java
src/main/java/com/habitpay/habitpay/domain/participationstat/domain/ParticipationStat.java

챌린지 주최자 및 챌린지 참여자가 챌린지 시작 전에 챌린지를 취소하는 API 요청(`POST /challenges/{id}/cancel`)이 정상적으로 처리되지 않는 문제를 수정했습니다.
오류가 발생한 백엔드 로그는 다음과 같습니다.
>backend   | Hibernate: delete from challenge_enrollment where id=?
backend   | 2024-12-01T03:59:39.114Z  WARN 289 --- [io-8080-exec-10] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 0, SQLState: 23503
backend   | 2024-12-01T03:59:39.114Z ERROR 289 --- [io-8080-exec-10] o.h.engine.jdbc.spi.SqlExceptionHelper   : ERROR: update or delete on table "challenge_enrollment" violates foreign key constraint "fkmx1pul0k5cnhr79cf0y70neht" on table "participation_stat"
backend   |   Detail: Key (id)=(4) is still referenced from table "participation_stat".
backend   | 2024-12-01T03:59:39.117Z  WARN 289 --- [io-8080-exec-10] .m.m.a.ExceptionHandlerExceptionResolver …

[fix] 챌린지 시작 전 취소 안되는 문제 수정#321

---

src/main/java/com/habitpay/habitpay/domain/member/application/MemberUpdateService.java
src/main/java/com/habitpay/habitpay/domain/postphoto/application/PostPhotoCreationService.java
src/main/java/com/habitpay/habitpay/domain/postphoto/application/PostPhotoUpdateService.java
src/main/java/com/habitpay/habitpay/global/util/ImageUtil.java
src/main/resources/application.yaml
src/test/resources/application.yaml

게시물 업로드 이미지와 프로필 업로드 이미지 파일의 크기 제한을 상향합니다.
최신 기종 스마트폰의 사진 품질이 높아서 모바일에서 이미지를 업로드 하지 못하는 문제를 해결하기 위한 방안입니다. (10MB 넘는 경우도 있음)
||1개당 용량|개수|총 용량|
|---|---|---|---|
|기존|1MB|5개|5MB|
|변경|10MB|5개|50MB|
||1개당 용량|개수|총 용량|
|---|---|---|---|
|기존|1MB|1개|1MB|
|변경|10MB|1개|10MB|
기존에 `ImageUtil` 클래스에서 하드 코딩으로 관리했던 이미지 파일 크기를 `application.yaml` 파일에서 일괄적으로 관리하도록 했습니다.
유지보수 할 때 설정값을 관리하는 지점을 하나로 통합하여 관리의 복잡성을 줄이기 위해 이와 같이 변경했습니다.
기존에 static 클래스였던 `ImageUtil`는 외부에서 값을 주입받기 때문에 `@Component` 어노테이션을 이용해서 Bean으로 등록했습니다.
또한, 서비스 계층에서는 의존성을 주입하여 사용하도록 변경했습니다.
```java
// ImageUtil.java
public class ImageUtil {
public static final long MB = 1024 * 1024;
public static final long PROFILE_IMAGE_SIZE_LIMIT = 1 * MB;
// ...
}
```
```java
// MemberUpdateService.java
if (ImageUtil.isValidFileSize(contentLength) == false) { …
```

[feat] 게시물 이미지 프로필 이미지 업로드 파일 크기 제한 상향#327

---

src/docs/asciidoc/api/challenge.adoc
src/main/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApi.java
src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeMemberSearchService.java
src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengeEnrolledMember.java
src/main/java/com/habitpay/habitpay/domain/challengeenrollment/dao/ChallengeEnrollmentRepository.java
src/main/java/com/habitpay/habitpay/domain/member/application/MemberSearchService.java
src/test/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApiTest.java

* 챌린지 상세 페이지의 우상단에는, 챌린지에 가입한 멤버 중 상위 3명의 사진과 전체 인원 수가 미리보기로 제공됩니다.
* 이때 미리보기 구역을 클릭하면, 해당 챌린지에 등록되어 있는 멤버들의 데이터를 제공하는 API를 추가했습니다.
---
* 특정 챌린지 내 등록된 멤버들의 데이터 리스트를 제공하는 API 메서드입니다.
```java
// ChallengeApi.java
@GetMapping("/challenges/{id}/members")
public SuccessResponse<List<ChallengeEnrolledMember>> getEnrolledMemberList(@PathVariable("id") Long id,
@AuthenticationPrincipal CustomUserDetails user) {
return challengeMemberSearchService.getEnrolledMemberList(id, user.getMember());
}
```
---
* 필요한 데이터를 담는 `ChallengeEnrolledMember DTO`를 만들었습니다.
```java
// challenge/dto/ChallengeEnrolledMember.java
public class ChallengeEnrolledMember {
private Long memberId;
private String nickname;
private String profileImageUrl;
private Boolean isMyself;
public static ChallengeEnrolledMember of(Long id, …
```

[Feat] 챌린지 상세 페이지 우상단의 멤버들 사진을 클릭하면, 챌린지 등록 멤버들 데이터 얻기 #330

---

build.gradle
src/docs/asciidoc/api/challengePost.adoc
src/main/java/com/habitpay/habitpay/domain/challengepost/api/ChallengePostApi.java
src/main/java/com/habitpay/habitpay/domain/challengepost/domain/ChallengePost.java
src/main/java/com/habitpay/habitpay/domain/challengepost/dto/AddPostRequest.java
src/main/java/com/habitpay/habitpay/domain/challengepost/dto/ModifyPostRequest.java
src/main/java/com/habitpay/habitpay/global/error/ErrorResponse.java
src/main/java/com/habitpay/habitpay/global/error/exception/ErrorCode.java
src/main/java/com/habitpay/habitpay/global/handler/GlobalExceptionHandler.java
src/main/resources/db/migration/V202412281745__Change_challengepost_content_length.sql
src/test/java/com/habitpay/habitpay/domain/challegepost/api/ChallengePostApiTest.java

게시물 내용이 255자 이상인 경우 백엔드에서 아래의 오류가 발생했습니다.
>could not execute statement[
ERROR: value too long for type character varying(255)
길이 제한을 1,000자로 상향하고, DTO 길이를 검증하는 로직을 추가했습니다. 
`@Column` 어노테이션에 length 속성을 이용해서 길이 제한을 255자에서 1,000자로 수정했습니다.
```java
// challengepost/domain/ChallengePost.java
@Column(length = 1000)
private String content;
```
PostgreSQL에서는 기본적으로 String을 `varchar(255)`으로 저장합니다. 그래서 이를 `varchar(1000)`로 변경해주었습니다.
참고로 1GB 용량의 텍스트를 저장할 수 있는 `text` 데이터 타입도 존재하지만, 의도적으로 긴 문자열을 전송해서 서버의 용량을 소모하는 공격을 제한하기 위해 사용하지 않았습니다. 
DB에서 챌린지 게시물 내용 컬럼의 길이를 `varchar(255)`에서 `varchar(1000)`으로 변경하기 위해 sql 파일을 추가했습니다.
```sql
ALTER TABLE challenge_post
ALTER COLUMN content TYPE varchar(1000);
```
Bean Validation을 이용하면 어노테이션을 이용해서 제약 조건을 생성할 수 있습니다.
1. 컨트롤러의 매개변수에 `@Valid` 어노테이션을 추가합니다.
```java
// …
```

Fix/게시물 내용 255자 제한 상향#335

---

src/docs/asciidoc/api/member.adoc
src/main/java/com/habitpay/habitpay/domain/member/api/MemberApi.java
src/main/java/com/habitpay/habitpay/domain/member/application/MemberDetailsService.java
src/main/java/com/habitpay/habitpay/domain/member/dto/MemberDetailsResponse.java
src/test/java/com/habitpay/habitpay/domain/member/api/MemberApiTest.java

* 현재 요청한 `사용자 본인`의 프로필 데이터를 불러오는 `GET /api/member` 컨트롤러가 존재합니다.
* 그러나 `다른 멤버의 챌린지 목록`을 불러올 수 있게 되면서, 동시에 `다른 멤버의 프로필 데이터`가 필요해졌습니다.
* 이에 `다른 멤버`의 `프로필 상세 정보`를 얻는 api를 추가했습니다.
---
```java
// MemberApi.java
@GetMapping("/members/{id}")
public SuccessResponse<MemberDetailsResponse> getMemberDetails(
@PathVariable("id") Long id,
@AuthenticationPrincipal CustomUserDetails user) {
return memberDetailsService.getMemberDetails(id, user.getMember());
}
```
* 상세 정보를 얻고 싶은 `멤버의 id`를 경로 변수로 받습니다.
---
```java
// member/dto/MemberDetailsResponse.java
public class MemberDetailsResponse {
private Long memberId;
private String nickname;
private String imageUrl;
private Boolean isCurrentUser;
...
}
```
* 기존에 본인의 프로필 데이터를 제공하는 DTO인 `MemberProfileResponse`과의 차이는 `Long memberId`, `Boolean isCurrentUser` 요소의 …

[Feat] 다른 멤버의 프로필 상세 정보를 얻는 api 추가#344

---

src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengePageResponse.java
src/test/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApiTest.java

챌린지 목록을 불러오는 `GET /challenges` API의 DTO에 챌린지 기간 동안 참여해야 하는 요일 수를 보여주는 `totalParticipatingDaysCount` 변수를 추가합니다.

[fix] GET /challenges 챌린지 총 참여 일수 dto 변수 추가#347

---

src/main/java/com/habitpay/habitpay/domain/challengeabsencefee/dto/MemberFeeView.java
src/main/java/com/habitpay/habitpay/domain/challengeenrollment/dao/ChallengeEnrollmentRepository.java

* `챌린지 상세 화면`의 `벌금 현황` 페이지에서 `달성율`이 올바르게 표시되지 않는 문제가 있었습니다.
* 소름 돋는 이야기인데요,
* 나눗셈 계산에서 식을 가당치 않게 썼기 때문입니다.
* 이를 고쳤습니다.
---
```java
// ChallengeEnrollmentRepository.java
@Query("SELECT new com...MemberFeeView(..., (s.successCount * 1.0 / :totalCount) * 100) " +
...)
List<MemberFeeView> findMemberFeeViewByChallenge(...);
```
* 기존 달성율을 구하는 식은 `(s.successCount / :totalCount) * 100)`였습니다.
* `전체 참여해야 하는 횟수` 중 `성공 횟수`의 비율을 구하는 식입니다.
* 그러나 `/` 연산은 `몫`만 취하기에, 100% 성공을 의미하는 `1`이 나오지 않는다면 (`나머지`를 무시하므로) 모두 `0%`로 계산됩니다.
* 어쩐지 `100%` 아니면 `0%`만 있더라니..
* 소름 돋을 정도로 가당치 않은 식이었습니다..
---
* `나머지`를 유의미하게 계산하기 위해, 데이터 타입을 `부동소수점`으로 바꿀 필요가 있습니다.
* `Cast`를 이용한 명시적 타입 변환 방법도 있고 이는 `PostgresQL`에서 지원하는 문법이기도 했으나,
* 좀 더 DB 독립적인 방법이라는 `* 1.0`식을 이용해 데이터 타입을 변환했습니다.
* 최종 식은 `(s.successCount * 1.0 / :totalCount) * …

[fix] 벌금 현황 페이지에서 달성율이 올바르게 표시되지 않는 문제 해결 #352

---

scripts/down-running-container.sh

이전에 실행했던 도커 컨테이너의 이미지 이름이 저장되지 않아서 수정했습니다.

[fix] 이전 실행 도커 이미지 삭제#355

---

scripts/switch.sh

기존 스크립트에서 nginx 파일을 원본으로 돌리면 green으로 리버스 프록싱 하도록 되어있었습니다. 그러다보니 nginx에서 스위칭을 수행할 때 실제로는 blue 컨테이너가 켜져있는 상황인데, 설정 파일에는 green 컨테이너가 실행되고 있는 것으로 판단해서 정상적인 스위칭이 일어나지 않았습니다. 이를 수정하기 위해 컨테이너 실행 시간을 비교하여 스위칭 하도록 했습니다.

[fix] nginx 변경 시 컨테이너 실행 시간 기준으로 비교 #355

---

scripts/switch.sh

[fix] 조건문 수정 #355

---

scripts/down-running-container.sh

찐찐찐찐찐막...
기존에 실행 중인 컨테이너 종료하기 전에 30초 딜레이를 추가했습니다. nginx 스위칭이 이루어지지 않은 상황에서 기존 실행 컨테이너를 종료하면 nginx가 upstream을 찾지 못하는 오류를 방지하기 위해서입니다.

[fix] 배포 shell script 수정 #355

---

src/docs/asciidoc/api/challenge.adoc
src/main/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApi.java
src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeSettlementService.java
src/main/java/com/habitpay/habitpay/domain/challenge/domain/Challenge.java
src/main/java/com/habitpay/habitpay/domain/challengescheduler/application/SchedulerTaskHelperService.java
src/main/java/com/habitpay/habitpay/global/error/exception/ErrorCode.java
src/main/java/com/habitpay/habitpay/global/response/SuccessCode.java
src/test/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApiTest.java

* `챌린지`가 (중간 취소 등 없이) 정상적으로 `종료`되면 `COMPLETED_PENDING_SETTLEMENT`의 상태가 됩니다.
* 이 상태는 챌린지가 종료되었으나 아직 `정산되지 않았음`을 의미합니다.
* 이때 `정산` API를 추가하여 벌금 처리 등 챌린지를 완료할 수 있도록 합니다.
* 이때 챌린지의 상태가 `COMPLETED_SETTLED`로 변경됩니다.
* 또한 챌린지 내 `isPaidAll` 변수값이 `true`로 변경됩니다.
* 현재는 앱 내 벌금 결제나 분배 등 다른 기능이 없으므로, 호스트가 자율적으로 정산하게 됩니다.
---
```java
// ChallengeApi.java
@PostMapping("/challenges/{id}/settlement")
public SuccessResponse<Void> setChallengeSettled(@PathVariable("id") Long id,
@AuthenticationPrincipal CustomUserDetails user) {
return challengeSettlementService.settleChallenge(id, user.getMember());
}
```
---
```java
// challenge/application/ChallengeSettlementService.java
public class ChallengeSettlementService {
...
public SuccessResponse<Void> settleChallenge(Long challengeId, Member member) {
Challenge …
```

[feat] 챌린지 종료 이후 정산하는 API 생성 #362
