- Dockerfile.dev
- build.gradle
- entrypoint.sh
- src/main/resources/application-development.properties
- src/main/resources/application.properties
- 자세한 내용은 #3 참고 부탁드립니다.
- [Boost Your Productivity: Enabling Hot Reload for Your Dockerized Spring Boot Kotlin Project](https://medium.com/@yiotiskl/boost-your-productivity-enabling-hot-reload-for-your-dockerized-spring-boot-kotlin-project-9aea60a53db1) [medium]
> Chore/개발환경 dockerfile 작성#3

- build.gradle
- src/main/java/com/habitpay/habitpay/HabitpayApplication.java
- src/main/java/com/habitpay/habitpay/config/auth/CorsConfig.java
- src/main/java/com/habitpay/habitpay/config/auth/CustomOAuth2UserService.java
- src/main/java/com/habitpay/habitpay/config/auth/SecurityConfig.java
- src/main/java/com/habitpay/habitpay/config/auth/dto/OAuthAttributes.java
- src/main/java/com/habitpay/habitpay/config/auth/dto/SessionUser.java
- src/main/java/com/habitpay/habitpay/user/entities/BaseTimeEntity.java
- src/main/java/com/habitpay/habitpay/user/entities/User.java
- src/main/java/com/habitpay/habitpay/user/enums/Role.java
- src/main/java/com/habitpay/habitpay/user/repositories/UserRepository.java
- src/main/resources/application.properties
Spring Security 와 Spring OAuth2 프레임워크를 이용해서 Google OAuth 회원가입을 구현했습니다.
- cors 허용 (`http://localhost:3000`)
- session 으로 로그인 정보 관리 중 (jwt 토큰 방식으로 변경 예정)
- 회원 정보를 DB 에 저장 (구글에서 email 과 username 만 받아서 저장함)
> Feat/google oauth 소셜 로그인 구현#5

- src/main/java/com/habitpay/habitpay/domain/member/api/MemberApi.java
- src/main/java/com/habitpay/habitpay/domain/member/application/MemberProfileService.java
- src/main/java/com/habitpay/habitpay/global/config/auth/CustomOAuth2LoginSuccessHandler.java
- 프론트에서 소셜 로그인 후 `isActive` 상태가 true 인 회원은 `/challenges/my_challenge` 로 리다이렉트 합니다.
> [WIP] Feat/챌린지 생성 기능 구현#26

- src/main/java/com/habitpay/habitpay/domain/challengeenrollment/api/ChallengeEnrollmentApi.java
- src/main/java/com/habitpay/habitpay/domain/challengeenrollment/application/ChallengeCancellationService.java
- src/main/java/com/habitpay/habitpay/domain/challengeenrollment/application/ChallengeEnrollmentService.java
- src/main/java/com/habitpay/habitpay/global/common/response/ApiResponse.java
- POST `/challenges/{id}enroll` 컨트롤러에서 서비스 로직을 분리했습니다. 
- `@AuthenticationPrincipal` 어노테이션을 적용해서 사용자의 이메일을 받아옵니다.
```java
// ChallengeEnrollmentApi.java
@PostMapping("/challenges/{id}/enroll")
@ResponseStatus(HttpStatus.OK)
public ResponseEntity<ApiResponse> enrollChallenge(@PathVariable("id") Long id, @AuthenticationPrincipal String email) {
log.info("[POST /challenges/{}/enroll] email: {}", id, email);
return challengeEnrollmentService.enroll(id, email);
}
```
- String 자료형만 반환하는 DTO 를 위한 클래스를 생성했습니다.
```java
@Getter
@AllArgsConstructor
public class ApiResponse {
private String message;
// 정적 팩토리 메서드
public static ApiResponse create(String message) {
return new ApiResponse(message);
}
}
```
- 해당 클래스는 정적 팩토리 메서드를 이용해서 객체를 반환하여 아래와 같이 사용할 수 있습니다. 
```java
ApiResponse response = …
```
> [Refactor] 챌린지 참여 컨트롤러 코드 리팩토링#71

- src/main/java/com/habitpay/habitpay/domain/challenge/api/ChallengeApi.java
- src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeDetailService.java
ChallengeDetailService 의 메서드 이름을 Repository 메서드와 일치하도록 변경했습니다. (getChallengeDetailById -> findById)
> :recycle: refactor: ChallengeDetailService 메서드 이름 변경 #85

- src/main/java/com/habitpay/habitpay/domain/challengeparticipationrecord/domain/ChallengeParticipationRecord.java
- src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostCreationService.java
- src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostDeleteService.java
- src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostSearchService.java
- src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostUpdateService.java
- src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostUtilService.java
- src/main/java/com/habitpay/habitpay/domain/challengepost/domain/ChallengePost.java
- src/main/java/com/habitpay/habitpay/domain/challengepost/dto/AddPostRequest.java
- src/main/java/com/habitpay/habitpay/domain/challengepost/dto/PostViewResponse.java
- src/main/java/com/habitpay/habitpay/domain/postphoto/application/PostPhotoDeleteService.java
- src/main/java/com/habitpay/habitpay/domain/postphoto/application/PostPhotoSearchService.java
- src/main/java/com/habitpay/habitpay/domain/postphoto/application/PostPhotoUtilService.java
- src/main/java/com/habitpay/habitpay/domain/postphoto/dao/PostPhotoRepository.java
- src/main/java/com/habitpay/habitpay/domain/postphoto/domain/PostPhoto.java
- src/main/java/com/habitpay/habitpay/domain/refreshtoken/application/RefreshTokenCreationService.java
- src/main/java/com/habitpay/habitpay/domain/refreshtoken/dao/RefreshTokenRepository.java
- src/main/java/com/habitpay/habitpay/domain/refreshtoken/domain/RefreshToken.java
* 도메인 내 요소의 외래키 연결을 완료했습니다.
```java
// 예를 들어 아래처럼 임시로 설정해놓은 코드를,
@Column
priviate Long memberId;
// 아래처럼 제대로 외래키 연결!
@ManyToOne
@JoinColumn
private Member member;
```
---
* 도메인 내에서 외래키 연결하는 요소의 경우, 쿼리 메서드 등 DB와 연결되는 과정에서 혼동을 방지하기 위해 변수명을 엔티티명과 최대한 동일하게 맞췄습니다.
```java
// before example
@JoinColumn
private ChallengeEnrollment enrollment;
// after example
@JoinColumn
private ChallengeEnrollment challengeEnrollment;
```
---
* 외래키가 연결되면서, 도메인 내 관련 요소를 이용하는 메서드를 데이터 타입에 맞게 수정 및 리팩토링 했습니다.
---
* S3 서비스에 사진을 업로드 및 불러오기 시 필요한 path를 만드는 target url을 만드는 메서드를 만들었습니다.
```java
public String makeS3TargetPath(PostPhoto photo) {
ChallengePost post = photo.getChallengePost();
return this.POST_PHOTOS_PREFIX +
"/" +
post.getChallengeEnrollment().getChallenge().getId() +
"/" +
post.getId();
}
// 결과물 : …
```
> Feat/domain primary key#99

- src/main/java/com/habitpay/habitpay/global/config/SchedulerConfiguration.java
* 스케쥴러 기능을 위한 설정 클래스인 `SchedulerConfiguration` 파일을 추가했습니다.
---
* 위치는 `config 패키지` 하위입니다.
(`JpaConfiguration`와 기능적으로 비슷하다고 판단하여 동일한 선상에 두었습니다.)
```java
src/main/java/com/habitpay/habitpay/global/config/
├── JpaConfiguration.java
├── SchedulerConfiguration.java
```
---
* 코드는 다음과 같습니다. (`JpaConfiguration`과 흡사합니다.)
```java
@Configuration
@EnableScheduling
public class SchedulerConfiguration {
}
```
---
* 이후 적용을 원하는 메서드에 `@Scheduled()`어노테이션을 붙이면 어디서든 스케쥴러 기능을 사용할 수 있습니다.
> [feat] SchedulerConfiguration 클래스 생성 #113

- src/main/java/com/habitpay/habitpay/domain/ChallengeAbsenceFee/application/ChallengeAbsenceFeeSearchService.java
- src/main/java/com/habitpay/habitpay/domain/challengeenrollment/application/ChallengeEnrollmentSearchService.java
- src/main/java/com/habitpay/habitpay/domain/challengeenrollment/dao/ChallengeEnrollmentRepository.java
- src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostCreationService.java
- src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostSearchService.java
* 위치
```java
// 도메인 패키지에 ChallengeAbsenceFee 패키지 생성
./src/main/java/com/habitpay/habitpay/domain/ChallengeAbsenceFee
└── application
└── ChallengeAbsenceFeeSearchService.java
```
---
* 주요 코드
```java
// ChallengeAbsenceFee/application/ChallengeAbsenceFeeSearchService.java
// member, challenge 정보를 통해 개인의 벌금 현황 조회
public int findPersonalTotalFeeOfChallenge(Member member, Challenge challenge) {
Optional<ChallengeEnrollment> optionalEnrollment = challengeEnrollmentSearchService.findByMemberAndChallenge(member, challenge);
return optionalEnrollment.map(ChallengeEnrollment::getTotalFee).orElse(0);
}
// enrollment 정보를 통해 개인의 벌금 현황 조회
public int findPersonalTotalFeeOfChallenge(ChallengeEnrollment enrollment) {
return enrollment.getTotalFee();
}
// 인자가 어떻게 들어올지 몰라 일단 오버로드로 두 개 만들었습니다.
// 코드가 간단하여, …
```
> [feat] 벌금 현황 조회 서비스 만들기 & 멤버와 챌린지 정보로 enrollment 객체 찾기 서비스 #120

- src/docs/asciidoc/api/member.adoc
- src/test/java/com/habitpay/habitpay/domain/api/MemberApiTest.java
프로필 업데이트 컨트롤러 테스트 코드를 작성했습니다.
1. `PATCH /member/nickname`
2. `PATCH /member/image`
> Test/프로필 업데이트 테스트 코드 작성#135

- src/main/java/com/habitpay/habitpay/domain/challengepost/api/ChallengePostApi.java
- src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostSearchService.java
- src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostUtilService.java
* 컨트롤러 메서드에서 디폴트값 없이 바로 Pageable 객체를 받습니다.
* Pageable 내에 자체적인 검증 로직이 있기 때문에, 어설픈 검증 메서드도 삭제했습니다.
* 깔끔!
> [remove] Pageable과 관련된 불필요한 설정 및 메서드 삭제하기 #168

- src/main/java/com/habitpay/habitpay/global/handler/GlobalExceptionHandler.java
* 이전에 테스트할 때 편하게 보려고 에러 메시지를 클래스명만 출력되도록 잠시 고쳤었음
* 그걸 원래대로 복원했습니다.
> [change] 글로벌 예외 핸들러를 원래 코드로 복원 #234

- down-running-container.sh
PR 을 main 브랜치로 merge 할 때 실행하는 GitHub Actions 에서 `down-running-container.sh` 스크립트 파일이 실행되지 않는 문제를 수정했습니다.
> :bug: fix: docker 명령어 앞 sudo 추가 및 컨테이너 종료 명령어 변경 #258

- .github/workflows/ci.yaml
- src/test/java/com/habitpay/habitpay/domain/challegepost/api/ChallengePostApiTest.java
main 브랜치를 향한 PR 이 생성되면 스프링 부트를 빌드(테스트 코드 실행 포함)하는 GitHub Actions 를 생성했습니다.
해당 액션이 정상적으로 종료되지 않으면 main 브랜치로 merge 할 수 없도록 설정했습니다.
> chore: CI GitHub Actions 추가 #263

- src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeCreationService.java
- src/main/java/com/habitpay/habitpay/domain/challenge/application/ChallengeSearchService.java
- src/main/java/com/habitpay/habitpay/domain/challenge/domain/Challenge.java
- src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostUtilService.java
> [feat] 챌린지 시작일, 참여 요일, record 등록 등에 관련된 시간 데이터 정합성 이해 및 설정 #270

- src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostUtilService.java
* 이전에 챌린지 진행 기간임에도 포스트가 업로드되지 않는 에러 상황이 발생함
(스크럼 중 발생)
* 문제를 해결하기 위해 코드를 봤는데 눈에 띄는 문제는 없었음
* 중간중간 풀리퀘 작업하며 타임존이 수정되기도 했는데, 이때 해결된 걸지도?
* 아무튼 당장은 에러가 발생하는 조건을 파악 못해서, 코드 보다가 리팩토링한 것만 풀리퀘 올립니다.
> [refact] verifyChallengePostForRecord 리팩토링 #296

- src/main/java/com/habitpay/habitpay/domain/challenge/dto/ChallengeRecords.java
- src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostUtilService.java
* 작은 리팩토링을 진행했습니다.
---
* `challenge/dto/ChallengeRecords` 클래스의 불필요한 `setter` 어노테이션을 삭제했습니다.
* `ChallengePostUtilService` 클래스의 `verifyChallengePostForRecord` 메서드에서, `boolean` 변수의 이름이 코드 커스텀에 맞게 `is`로 시작하도록 변경했습니다.
> [refactor] 작은 리팩토링(코멘트 받은 것 반영) #306

- src/main/java/com/habitpay/habitpay/domain/challengepost/api/ChallengePostApi.java
- src/main/java/com/habitpay/habitpay/domain/challengepost/application/ChallengePostSearchService.java
- src/main/java/com/habitpay/habitpay/domain/challengepost/domain/ChallengePost.java
- src/main/java/com/habitpay/habitpay/domain/challengepost/dto/PostViewResponse.java
- src/main/java/com/habitpay/habitpay/domain/member/domain/Member.java
- src/test/java/com/habitpay/habitpay/domain/challegepost/api/ChallengePostApiTest.java
* 포스트 데이터를 담는 DTO인 `PostViewResponse` 클래스에 `Boolean` `isPostAuthor` 속성을 추가했습니다.
* 데이터를 요청한 멤버가 해당 `포스트의 작성자인지 여부`를 알려주는 속성입니다.
* 프론트에서 포스트 별 수정 및 삭제 버튼을 활성화할지 여부를 판단할 때 사용할 수 있을 것으로 보입니다.
---
```java
// PostViewResponse.java
public class PostViewResponse {
...
private String writer;
private Boolean isPostAuthor;
...
public PostViewResponse(ChallengePost post, Boolean isPostAuthor, ...) {
...
this.writer = post.getWriter().getNickname();
this.isPostAuthor = isPostAuthor;
...
}
}
```
* `PostViewResponse` DTO에 작성자 닉네임 뿐만 아니라 작성자 여부를 확인하는 `isPostAuthor` 속성을 추가했습니다.
---
* 데이터를 요청한 멤버의 정보가 추가로 필요하기 때문에,
`ChallengePostApi` 메서드에서 필요한 경우 `User 인자`를 추가로 받도록 수정했습니다.
```java
// ChallengePostApi.java
// ex
//before
@GetMapping("/challenges/{id}/posts")
public SuccessResponse<Slice<PostViewResponse>> …
```
> [feat] 챌린지 포스트 뷰 데이터에, 데이터 요청 멤버가 작성자 본인인지 여부 알려주는 속성 추가 #312

- docker-compose.yaml
- git-pull.sh
무중단 배포를 위한 bash script 및 docker compose 수정
> chore: nginx 설정 파일 초기화 명령어 추가 #337

- scripts/switch.sh
> fix: nginx 설정 파일 위치 변경 #337

- git-pull.sh
- scripts/deploy.sh
- scripts/switch.sh
nginx 설정 파일을 변경하지 못하는 문제를 수정했습니다.
> [fix]배포 shell script 수정#355
